// Code generated by protoc-gen-go.
// source: dzhua.proto
// DO NOT EDIT!

package dzhyun

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UAResponse struct {
	Qid     string `protobuf:"bytes,1,opt,name=Qid" json:"Qid,omitempty"`
	Err     int32  `protobuf:"varint,2,opt,name=Err" json:"Err,omitempty"`
	Counter uint32 `protobuf:"varint,3,opt,name=Counter" json:"Counter,omitempty"`
	Data    []byte `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *UAResponse) Reset()                    { *m = UAResponse{} }
func (m *UAResponse) String() string            { return proto.CompactTextString(m) }
func (*UAResponse) ProtoMessage()               {}
func (*UAResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *UAResponse) GetQid() string {
	if m != nil {
		return m.Qid
	}
	return ""
}

func (m *UAResponse) GetErr() int32 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *UAResponse) GetCounter() uint32 {
	if m != nil {
		return m.Counter
	}
	return 0
}

func (m *UAResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ChildResponse struct {
	No   int32  `protobuf:"varint,1,opt,name=No" json:"No,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *ChildResponse) Reset()                    { *m = ChildResponse{} }
func (m *ChildResponse) String() string            { return proto.CompactTextString(m) }
func (*ChildResponse) ProtoMessage()               {}
func (*ChildResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *ChildResponse) GetNo() int32 {
	if m != nil {
		return m.No
	}
	return 0
}

func (m *ChildResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GroupResponse struct {
	ChildRes []*ChildResponse `protobuf:"bytes,1,rep,name=ChildRes" json:"ChildRes,omitempty"`
}

func (m *GroupResponse) Reset()                    { *m = GroupResponse{} }
func (m *GroupResponse) String() string            { return proto.CompactTextString(m) }
func (*GroupResponse) ProtoMessage()               {}
func (*GroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *GroupResponse) GetChildRes() []*ChildResponse {
	if m != nil {
		return m.ChildRes
	}
	return nil
}

func init() {
	proto.RegisterType((*UAResponse)(nil), "dzhyun.UAResponse")
	proto.RegisterType((*ChildResponse)(nil), "dzhyun.ChildResponse")
	proto.RegisterType((*GroupResponse)(nil), "dzhyun.GroupResponse")
}

func init() { proto.RegisterFile("dzhua.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xa9, 0xca, 0x28,
	0x4d, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xa9, 0xca, 0xa8, 0x2c, 0xcd, 0x53,
	0x8a, 0xe3, 0xe2, 0x0a, 0x75, 0x0c, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe0,
	0x62, 0x0e, 0xcc, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x41, 0x22, 0xae,
	0x45, 0x45, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x20, 0xa6, 0x90, 0x04, 0x17, 0xbb, 0x73,
	0x7e, 0x69, 0x5e, 0x49, 0x6a, 0x91, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x8c, 0x2b, 0x24,
	0xc4, 0xc5, 0xe2, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x2b,
	0x19, 0x73, 0xf1, 0x3a, 0x67, 0x64, 0xe6, 0xa4, 0xc0, 0xad, 0xe0, 0xe3, 0x62, 0xf2, 0xcb, 0x07,
	0xdb, 0xc0, 0x1a, 0xc4, 0xe4, 0x97, 0x0f, 0xd7, 0xc4, 0x84, 0xa4, 0xc9, 0x89, 0x8b, 0xd7, 0xbd,
	0x28, 0xbf, 0xb4, 0x00, 0xae, 0xc9, 0x90, 0x8b, 0x03, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xb3, 0x06,
	0xb7, 0x91, 0xa8, 0x1e, 0xc4, 0x03, 0x7a, 0x28, 0xa6, 0x07, 0xc1, 0x95, 0x39, 0x09, 0x71, 0x09,
	0x24, 0xe7, 0xe7, 0xc2, 0x54, 0x81, 0x3d, 0x9d, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x8d, 0xb2, 0x80, 0x33, 0x0a, 0x01, 0x00, 0x00,
}
