// Code generated by protoc-gen-go.
// source: dzhyun.gupiaoqiepian.proto
// DO NOT EDIT!

package dzhyun

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FenBiChengJiao struct {
	Id                      YFloat `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	ShiJian                 YFloat `protobuf:"varint,2,opt,name=ShiJian" json:"ShiJian,omitempty"`
	ChengJiaoJia            YFloat `protobuf:"varint,3,opt,name=ChengJiaoJia" json:"ChengJiaoJia,omitempty"`
	ChengJiaoLiang          YFloat `protobuf:"varint,4,opt,name=ChengJiaoLiang" json:"ChengJiaoLiang,omitempty"`
	ChengJiaoE              YFloat `protobuf:"varint,5,opt,name=ChengJiaoE" json:"ChengJiaoE,omitempty"`
	ChengJiaoDanBiShu       YFloat `protobuf:"varint,6,opt,name=ChengJiaoDanBiShu" json:"ChengJiaoDanBiShu,omitempty"`
	ShiFouZhuDongXingMaiDan YFloat `protobuf:"varint,7,opt,name=ShiFouZhuDongXingMaiDan" json:"ShiFouZhuDongXingMaiDan,omitempty"`
	MaiMaiFangXiang         YFloat `protobuf:"varint,8,opt,name=MaiMaiFangXiang" json:"MaiMaiFangXiang,omitempty"`
	DanCiChengJiaoLiang     YFloat `protobuf:"varint,9,opt,name=DanCiChengJiaoLiang" json:"DanCiChengJiaoLiang,omitempty"`
	DanCiChengJiaoE         YFloat `protobuf:"varint,10,opt,name=DanCiChengJiaoE" json:"DanCiChengJiaoE,omitempty"`
	DanCiChengJiaoDanBiShu  YFloat `protobuf:"varint,11,opt,name=DanCiChengJiaoDanBiShu" json:"DanCiChengJiaoDanBiShu,omitempty"`
}

func (m *FenBiChengJiao) Reset()                    { *m = FenBiChengJiao{} }
func (m *FenBiChengJiao) String() string            { return proto.CompactTextString(m) }
func (*FenBiChengJiao) ProtoMessage()               {}
func (*FenBiChengJiao) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *FenBiChengJiao) GetId() YFloat {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FenBiChengJiao) GetShiJian() YFloat {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *FenBiChengJiao) GetChengJiaoJia() YFloat {
	if m != nil {
		return m.ChengJiaoJia
	}
	return 0
}

func (m *FenBiChengJiao) GetChengJiaoLiang() YFloat {
	if m != nil {
		return m.ChengJiaoLiang
	}
	return 0
}

func (m *FenBiChengJiao) GetChengJiaoE() YFloat {
	if m != nil {
		return m.ChengJiaoE
	}
	return 0
}

func (m *FenBiChengJiao) GetChengJiaoDanBiShu() YFloat {
	if m != nil {
		return m.ChengJiaoDanBiShu
	}
	return 0
}

func (m *FenBiChengJiao) GetShiFouZhuDongXingMaiDan() YFloat {
	if m != nil {
		return m.ShiFouZhuDongXingMaiDan
	}
	return 0
}

func (m *FenBiChengJiao) GetMaiMaiFangXiang() YFloat {
	if m != nil {
		return m.MaiMaiFangXiang
	}
	return 0
}

func (m *FenBiChengJiao) GetDanCiChengJiaoLiang() YFloat {
	if m != nil {
		return m.DanCiChengJiaoLiang
	}
	return 0
}

func (m *FenBiChengJiao) GetDanCiChengJiaoE() YFloat {
	if m != nil {
		return m.DanCiChengJiaoE
	}
	return 0
}

func (m *FenBiChengJiao) GetDanCiChengJiaoDanBiShu() YFloat {
	if m != nil {
		return m.DanCiChengJiaoDanBiShu
	}
	return 0
}

type GeGuDongTai struct {
	Id                  YFloat `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	ShiJian             YFloat `protobuf:"varint,2,opt,name=ShiJian" json:"ShiJian,omitempty"`
	ZuiXinJia           YFloat `protobuf:"varint,3,opt,name=ZuiXinJia" json:"ZuiXinJia,omitempty"`
	KaiPanJia           YFloat `protobuf:"varint,4,opt,name=KaiPanJia" json:"KaiPanJia,omitempty"`
	ZuiGaoJia           YFloat `protobuf:"varint,5,opt,name=ZuiGaoJia" json:"ZuiGaoJia,omitempty"`
	ZuiDiJia            YFloat `protobuf:"varint,6,opt,name=ZuiDiJia" json:"ZuiDiJia,omitempty"`
	ZuoShou             YFloat `protobuf:"varint,7,opt,name=ZuoShou" json:"ZuoShou,omitempty"`
	JunJia              YFloat `protobuf:"varint,8,opt,name=JunJia" json:"JunJia,omitempty"`
	ZhangDie            YFloat `protobuf:"varint,9,opt,name=ZhangDie" json:"ZhangDie,omitempty"`
	ZhangFu             YFloat `protobuf:"varint,10,opt,name=ZhangFu" json:"ZhangFu,omitempty"`
	ZhenFu              YFloat `protobuf:"varint,11,opt,name=ZhenFu" json:"ZhenFu,omitempty"`
	ChengJiaoLiang      YFloat `protobuf:"varint,12,opt,name=ChengJiaoLiang" json:"ChengJiaoLiang,omitempty"`
	XianShou            YFloat `protobuf:"varint,13,opt,name=XianShou" json:"XianShou,omitempty"`
	ChengJiaoE          YFloat `protobuf:"varint,14,opt,name=ChengJiaoE" json:"ChengJiaoE,omitempty"`
	ZongChengJiaoBiShu  YFloat `protobuf:"varint,15,opt,name=ZongChengJiaoBiShu" json:"ZongChengJiaoBiShu,omitempty"`
	MeiBiChengJiaoGuShu YFloat `protobuf:"varint,16,opt,name=MeiBiChengJiaoGuShu" json:"MeiBiChengJiaoGuShu,omitempty"`
	HuanShou            YFloat `protobuf:"varint,17,opt,name=HuanShou" json:"HuanShou,omitempty"`
	LiangBi             YFloat `protobuf:"varint,18,opt,name=LiangBi" json:"LiangBi,omitempty"`
	NeiPan              YFloat `protobuf:"varint,19,opt,name=NeiPan" json:"NeiPan,omitempty"`
	WaiPan              YFloat `protobuf:"varint,20,opt,name=WaiPan" json:"WaiPan,omitempty"`
	// lv2数据
	ZongMaiRu        YFloat `protobuf:"varint,21,opt,name=ZongMaiRu" json:"ZongMaiRu,omitempty"`
	ZongMaiChu       YFloat `protobuf:"varint,22,opt,name=ZongMaiChu" json:"ZongMaiChu,omitempty"`
	ZongMaiRuJunJia  YFloat `protobuf:"varint,23,opt,name=ZongMaiRuJunJia" json:"ZongMaiRuJunJia,omitempty"`
	ZongMaiChuJunJia YFloat `protobuf:"varint,24,opt,name=ZongMaiChuJunJia" json:"ZongMaiChuJunJia,omitempty"`
	ZhangTing        YFloat `protobuf:"varint,25,opt,name=ZhangTing" json:"ZhangTing,omitempty"`
	DieTing          YFloat `protobuf:"varint,26,opt,name=DieTing" json:"DieTing,omitempty"`
	FenZhongZhangFu1 YFloat `protobuf:"varint,27,opt,name=FenZhongZhangFu1" json:"FenZhongZhangFu1,omitempty"`
	FenZhongZhangFu2 YFloat `protobuf:"varint,28,opt,name=FenZhongZhangFu2" json:"FenZhongZhangFu2,omitempty"`
	FenZhongZhangFu3 YFloat `protobuf:"varint,29,opt,name=FenZhongZhangFu3" json:"FenZhongZhangFu3,omitempty"`
	FenZhongZhangFu4 YFloat `protobuf:"varint,30,opt,name=FenZhongZhangFu4" json:"FenZhongZhangFu4,omitempty"`
	FenZhongZhangFu5 YFloat `protobuf:"varint,31,opt,name=FenZhongZhangFu5" json:"FenZhongZhangFu5,omitempty"`
	// 买卖盘
	WeiTuoMaiRuJia1    YFloat `protobuf:"varint,32,opt,name=WeiTuoMaiRuJia1" json:"WeiTuoMaiRuJia1,omitempty"`
	WeiTuoMaiRuLiang1  YFloat `protobuf:"varint,33,opt,name=WeiTuoMaiRuLiang1" json:"WeiTuoMaiRuLiang1,omitempty"`
	WeiTuoMaiRuJia2    YFloat `protobuf:"varint,34,opt,name=WeiTuoMaiRuJia2" json:"WeiTuoMaiRuJia2,omitempty"`
	WeiTuoMaiRuLiang2  YFloat `protobuf:"varint,35,opt,name=WeiTuoMaiRuLiang2" json:"WeiTuoMaiRuLiang2,omitempty"`
	WeiTuoMaiRuJia3    YFloat `protobuf:"varint,36,opt,name=WeiTuoMaiRuJia3" json:"WeiTuoMaiRuJia3,omitempty"`
	WeiTuoMaiRuLiang3  YFloat `protobuf:"varint,37,opt,name=WeiTuoMaiRuLiang3" json:"WeiTuoMaiRuLiang3,omitempty"`
	WeiTuoMaiRuJia4    YFloat `protobuf:"varint,38,opt,name=WeiTuoMaiRuJia4" json:"WeiTuoMaiRuJia4,omitempty"`
	WeiTuoMaiRuLiang4  YFloat `protobuf:"varint,39,opt,name=WeiTuoMaiRuLiang4" json:"WeiTuoMaiRuLiang4,omitempty"`
	WeiTuoMaiRuJia5    YFloat `protobuf:"varint,40,opt,name=WeiTuoMaiRuJia5" json:"WeiTuoMaiRuJia5,omitempty"`
	WeiTuoMaiRuLiang5  YFloat `protobuf:"varint,41,opt,name=WeiTuoMaiRuLiang5" json:"WeiTuoMaiRuLiang5,omitempty"`
	WeiTuoMaiChuJia1   YFloat `protobuf:"varint,42,opt,name=WeiTuoMaiChuJia1" json:"WeiTuoMaiChuJia1,omitempty"`
	WeiTuoMaiChuLiang1 YFloat `protobuf:"varint,43,opt,name=WeiTuoMaiChuLiang1" json:"WeiTuoMaiChuLiang1,omitempty"`
	WeiTuoMaiChuJia2   YFloat `protobuf:"varint,44,opt,name=WeiTuoMaiChuJia2" json:"WeiTuoMaiChuJia2,omitempty"`
	WeiTuoMaiChuLiang2 YFloat `protobuf:"varint,45,opt,name=WeiTuoMaiChuLiang2" json:"WeiTuoMaiChuLiang2,omitempty"`
	WeiTuoMaiChuJia3   YFloat `protobuf:"varint,46,opt,name=WeiTuoMaiChuJia3" json:"WeiTuoMaiChuJia3,omitempty"`
	WeiTuoMaiChuLiang3 YFloat `protobuf:"varint,47,opt,name=WeiTuoMaiChuLiang3" json:"WeiTuoMaiChuLiang3,omitempty"`
	WeiTuoMaiChuJia4   YFloat `protobuf:"varint,48,opt,name=WeiTuoMaiChuJia4" json:"WeiTuoMaiChuJia4,omitempty"`
	WeiTuoMaiChuLiang4 YFloat `protobuf:"varint,49,opt,name=WeiTuoMaiChuLiang4" json:"WeiTuoMaiChuLiang4,omitempty"`
	WeiTuoMaiChuJia5   YFloat `protobuf:"varint,50,opt,name=WeiTuoMaiChuJia5" json:"WeiTuoMaiChuJia5,omitempty"`
	WeiTuoMaiChuLiang5 YFloat `protobuf:"varint,51,opt,name=WeiTuoMaiChuLiang5" json:"WeiTuoMaiChuLiang5,omitempty"`
	WeiBi              YFloat `protobuf:"varint,52,opt,name=WeiBi" json:"WeiBi,omitempty"`
	WeiCha             YFloat `protobuf:"varint,53,opt,name=WeiCha" json:"WeiCha,omitempty"`
	// 扩展买卖盘
	JiaQuanPingJunWeiTuoMaiRuJia  YFloat `protobuf:"varint,54,opt,name=JiaQuanPingJunWeiTuoMaiRuJia" json:"JiaQuanPingJunWeiTuoMaiRuJia,omitempty"`
	WeiTuoMaiRuZongLiang          YFloat `protobuf:"varint,55,opt,name=WeiTuoMaiRuZongLiang" json:"WeiTuoMaiRuZongLiang,omitempty"`
	JiaQuanPingJunWeiTuoMaiChuJia YFloat `protobuf:"varint,56,opt,name=JiaQuanPingJunWeiTuoMaiChuJia" json:"JiaQuanPingJunWeiTuoMaiChuJia,omitempty"`
	WeiTuoMaiChuZongLiang         YFloat `protobuf:"varint,57,opt,name=WeiTuoMaiChuZongLiang" json:"WeiTuoMaiChuZongLiang,omitempty"`
	KuoZhanMaiRuJia1              YFloat `protobuf:"varint,58,opt,name=KuoZhanMaiRuJia1" json:"KuoZhanMaiRuJia1,omitempty"`
	KuoZhanMaiRuJia2              YFloat `protobuf:"varint,59,opt,name=KuoZhanMaiRuJia2" json:"KuoZhanMaiRuJia2,omitempty"`
	KuoZhanMaiRuJia3              YFloat `protobuf:"varint,60,opt,name=KuoZhanMaiRuJia3" json:"KuoZhanMaiRuJia3,omitempty"`
	KuoZhanMaiRuJia4              YFloat `protobuf:"varint,61,opt,name=KuoZhanMaiRuJia4" json:"KuoZhanMaiRuJia4,omitempty"`
	KuoZhanMaiRuJia5              YFloat `protobuf:"varint,62,opt,name=KuoZhanMaiRuJia5" json:"KuoZhanMaiRuJia5,omitempty"`
	KuoZhanMaiRuLiang1            YFloat `protobuf:"varint,63,opt,name=KuoZhanMaiRuLiang1" json:"KuoZhanMaiRuLiang1,omitempty"`
	KuoZhanMaiRuLiang2            YFloat `protobuf:"varint,64,opt,name=KuoZhanMaiRuLiang2" json:"KuoZhanMaiRuLiang2,omitempty"`
	KuoZhanMaiRuLiang3            YFloat `protobuf:"varint,65,opt,name=KuoZhanMaiRuLiang3" json:"KuoZhanMaiRuLiang3,omitempty"`
	KuoZhanMaiRuLiang4            YFloat `protobuf:"varint,66,opt,name=KuoZhanMaiRuLiang4" json:"KuoZhanMaiRuLiang4,omitempty"`
	KuoZhanMaiRuLiang5            YFloat `protobuf:"varint,67,opt,name=KuoZhanMaiRuLiang5" json:"KuoZhanMaiRuLiang5,omitempty"`
	KuoZhanMaiChuJia1             YFloat `protobuf:"varint,68,opt,name=KuoZhanMaiChuJia1" json:"KuoZhanMaiChuJia1,omitempty"`
	KuoZhanMaiChuJia2             YFloat `protobuf:"varint,69,opt,name=KuoZhanMaiChuJia2" json:"KuoZhanMaiChuJia2,omitempty"`
	KuoZhanMaiChuJia3             YFloat `protobuf:"varint,70,opt,name=KuoZhanMaiChuJia3" json:"KuoZhanMaiChuJia3,omitempty"`
	KuoZhanMaiChuJia4             YFloat `protobuf:"varint,71,opt,name=KuoZhanMaiChuJia4" json:"KuoZhanMaiChuJia4,omitempty"`
	KuoZhanMaiChuJia5             YFloat `protobuf:"varint,72,opt,name=KuoZhanMaiChuJia5" json:"KuoZhanMaiChuJia5,omitempty"`
	KuoZhanMaiChuLiang1           YFloat `protobuf:"varint,73,opt,name=KuoZhanMaiChuLiang1" json:"KuoZhanMaiChuLiang1,omitempty"`
	KuoZhanMaiChuLiang2           YFloat `protobuf:"varint,74,opt,name=KuoZhanMaiChuLiang2" json:"KuoZhanMaiChuLiang2,omitempty"`
	KuoZhanMaiChuLiang3           YFloat `protobuf:"varint,75,opt,name=KuoZhanMaiChuLiang3" json:"KuoZhanMaiChuLiang3,omitempty"`
	KuoZhanMaiChuLiang4           YFloat `protobuf:"varint,76,opt,name=KuoZhanMaiChuLiang4" json:"KuoZhanMaiChuLiang4,omitempty"`
	KuoZhanMaiChuLiang5           YFloat `protobuf:"varint,77,opt,name=KuoZhanMaiChuLiang5" json:"KuoZhanMaiChuLiang5,omitempty"`
	// 期货特有
	ChiCang         YFloat `protobuf:"varint,78,opt,name=ChiCang" json:"ChiCang,omitempty"`
	ZengCang        YFloat `protobuf:"varint,79,opt,name=ZengCang" json:"ZengCang,omitempty"`
	RiZeng          YFloat `protobuf:"varint,80,opt,name=RiZeng" json:"RiZeng,omitempty"`
	JieSuanJia      YFloat `protobuf:"varint,81,opt,name=JieSuanJia" json:"JieSuanJia,omitempty"`
	ZuoRiJieSuanJia YFloat `protobuf:"varint,82,opt,name=ZuoRiJieSuanJia" json:"ZuoRiJieSuanJia,omitempty"`
	KaiPing         YFloat `protobuf:"varint,83,opt,name=KaiPing" json:"KaiPing,omitempty"`
	JieSuanZhangDie YFloat `protobuf:"varint,84,opt,name=JieSuanZhangDie" json:"JieSuanZhangDie,omitempty"`
	JieSuanZhangFu  YFloat `protobuf:"varint,85,opt,name=JieSuanZhangFu" json:"JieSuanZhangFu,omitempty"`
	// 盘口变化
	PanKouBianHuaMaiRu1   YFloat `protobuf:"varint,86,opt,name=PanKouBianHuaMaiRu1" json:"PanKouBianHuaMaiRu1,omitempty"`
	PanKouBianHuaMaiRu2   YFloat `protobuf:"varint,87,opt,name=PanKouBianHuaMaiRu2" json:"PanKouBianHuaMaiRu2,omitempty"`
	PanKouBianHuaMaiRu3   YFloat `protobuf:"varint,88,opt,name=PanKouBianHuaMaiRu3" json:"PanKouBianHuaMaiRu3,omitempty"`
	PanKouBianHuaMaiRu4   YFloat `protobuf:"varint,89,opt,name=PanKouBianHuaMaiRu4" json:"PanKouBianHuaMaiRu4,omitempty"`
	PanKouBianHuaMaiRu5   YFloat `protobuf:"varint,90,opt,name=PanKouBianHuaMaiRu5" json:"PanKouBianHuaMaiRu5,omitempty"`
	PanKouBianHuaMaiRu6   YFloat `protobuf:"varint,91,opt,name=PanKouBianHuaMaiRu6" json:"PanKouBianHuaMaiRu6,omitempty"`
	PanKouBianHuaMaiRu7   YFloat `protobuf:"varint,92,opt,name=PanKouBianHuaMaiRu7" json:"PanKouBianHuaMaiRu7,omitempty"`
	PanKouBianHuaMaiRu8   YFloat `protobuf:"varint,93,opt,name=PanKouBianHuaMaiRu8" json:"PanKouBianHuaMaiRu8,omitempty"`
	PanKouBianHuaMaiRu9   YFloat `protobuf:"varint,94,opt,name=PanKouBianHuaMaiRu9" json:"PanKouBianHuaMaiRu9,omitempty"`
	PanKouBianHuaMaiRu10  YFloat `protobuf:"varint,95,opt,name=PanKouBianHuaMaiRu10" json:"PanKouBianHuaMaiRu10,omitempty"`
	PanKouBianHuaMaiChu1  YFloat `protobuf:"varint,96,opt,name=PanKouBianHuaMaiChu1" json:"PanKouBianHuaMaiChu1,omitempty"`
	PanKouBianHuaMaiChu2  YFloat `protobuf:"varint,97,opt,name=PanKouBianHuaMaiChu2" json:"PanKouBianHuaMaiChu2,omitempty"`
	PanKouBianHuaMaiChu3  YFloat `protobuf:"varint,98,opt,name=PanKouBianHuaMaiChu3" json:"PanKouBianHuaMaiChu3,omitempty"`
	PanKouBianHuaMaiChu4  YFloat `protobuf:"varint,99,opt,name=PanKouBianHuaMaiChu4" json:"PanKouBianHuaMaiChu4,omitempty"`
	PanKouBianHuaMaiChu5  YFloat `protobuf:"varint,100,opt,name=PanKouBianHuaMaiChu5" json:"PanKouBianHuaMaiChu5,omitempty"`
	PanKouBianHuaMaiChu6  YFloat `protobuf:"varint,101,opt,name=PanKouBianHuaMaiChu6" json:"PanKouBianHuaMaiChu6,omitempty"`
	PanKouBianHuaMaiChu7  YFloat `protobuf:"varint,102,opt,name=PanKouBianHuaMaiChu7" json:"PanKouBianHuaMaiChu7,omitempty"`
	PanKouBianHuaMaiChu8  YFloat `protobuf:"varint,103,opt,name=PanKouBianHuaMaiChu8" json:"PanKouBianHuaMaiChu8,omitempty"`
	PanKouBianHuaMaiChu9  YFloat `protobuf:"varint,104,opt,name=PanKouBianHuaMaiChu9" json:"PanKouBianHuaMaiChu9,omitempty"`
	PanKouBianHuaMaiChu10 YFloat `protobuf:"varint,105,opt,name=PanKouBianHuaMaiChu10" json:"PanKouBianHuaMaiChu10,omitempty"`
}

func (m *GeGuDongTai) Reset()                    { *m = GeGuDongTai{} }
func (m *GeGuDongTai) String() string            { return proto.CompactTextString(m) }
func (*GeGuDongTai) ProtoMessage()               {}
func (*GeGuDongTai) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *GeGuDongTai) GetId() YFloat {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GeGuDongTai) GetShiJian() YFloat {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *GeGuDongTai) GetZuiXinJia() YFloat {
	if m != nil {
		return m.ZuiXinJia
	}
	return 0
}

func (m *GeGuDongTai) GetKaiPanJia() YFloat {
	if m != nil {
		return m.KaiPanJia
	}
	return 0
}

func (m *GeGuDongTai) GetZuiGaoJia() YFloat {
	if m != nil {
		return m.ZuiGaoJia
	}
	return 0
}

func (m *GeGuDongTai) GetZuiDiJia() YFloat {
	if m != nil {
		return m.ZuiDiJia
	}
	return 0
}

func (m *GeGuDongTai) GetZuoShou() YFloat {
	if m != nil {
		return m.ZuoShou
	}
	return 0
}

func (m *GeGuDongTai) GetJunJia() YFloat {
	if m != nil {
		return m.JunJia
	}
	return 0
}

func (m *GeGuDongTai) GetZhangDie() YFloat {
	if m != nil {
		return m.ZhangDie
	}
	return 0
}

func (m *GeGuDongTai) GetZhangFu() YFloat {
	if m != nil {
		return m.ZhangFu
	}
	return 0
}

func (m *GeGuDongTai) GetZhenFu() YFloat {
	if m != nil {
		return m.ZhenFu
	}
	return 0
}

func (m *GeGuDongTai) GetChengJiaoLiang() YFloat {
	if m != nil {
		return m.ChengJiaoLiang
	}
	return 0
}

func (m *GeGuDongTai) GetXianShou() YFloat {
	if m != nil {
		return m.XianShou
	}
	return 0
}

func (m *GeGuDongTai) GetChengJiaoE() YFloat {
	if m != nil {
		return m.ChengJiaoE
	}
	return 0
}

func (m *GeGuDongTai) GetZongChengJiaoBiShu() YFloat {
	if m != nil {
		return m.ZongChengJiaoBiShu
	}
	return 0
}

func (m *GeGuDongTai) GetMeiBiChengJiaoGuShu() YFloat {
	if m != nil {
		return m.MeiBiChengJiaoGuShu
	}
	return 0
}

func (m *GeGuDongTai) GetHuanShou() YFloat {
	if m != nil {
		return m.HuanShou
	}
	return 0
}

func (m *GeGuDongTai) GetLiangBi() YFloat {
	if m != nil {
		return m.LiangBi
	}
	return 0
}

func (m *GeGuDongTai) GetNeiPan() YFloat {
	if m != nil {
		return m.NeiPan
	}
	return 0
}

func (m *GeGuDongTai) GetWaiPan() YFloat {
	if m != nil {
		return m.WaiPan
	}
	return 0
}

func (m *GeGuDongTai) GetZongMaiRu() YFloat {
	if m != nil {
		return m.ZongMaiRu
	}
	return 0
}

func (m *GeGuDongTai) GetZongMaiChu() YFloat {
	if m != nil {
		return m.ZongMaiChu
	}
	return 0
}

func (m *GeGuDongTai) GetZongMaiRuJunJia() YFloat {
	if m != nil {
		return m.ZongMaiRuJunJia
	}
	return 0
}

func (m *GeGuDongTai) GetZongMaiChuJunJia() YFloat {
	if m != nil {
		return m.ZongMaiChuJunJia
	}
	return 0
}

func (m *GeGuDongTai) GetZhangTing() YFloat {
	if m != nil {
		return m.ZhangTing
	}
	return 0
}

func (m *GeGuDongTai) GetDieTing() YFloat {
	if m != nil {
		return m.DieTing
	}
	return 0
}

func (m *GeGuDongTai) GetFenZhongZhangFu1() YFloat {
	if m != nil {
		return m.FenZhongZhangFu1
	}
	return 0
}

func (m *GeGuDongTai) GetFenZhongZhangFu2() YFloat {
	if m != nil {
		return m.FenZhongZhangFu2
	}
	return 0
}

func (m *GeGuDongTai) GetFenZhongZhangFu3() YFloat {
	if m != nil {
		return m.FenZhongZhangFu3
	}
	return 0
}

func (m *GeGuDongTai) GetFenZhongZhangFu4() YFloat {
	if m != nil {
		return m.FenZhongZhangFu4
	}
	return 0
}

func (m *GeGuDongTai) GetFenZhongZhangFu5() YFloat {
	if m != nil {
		return m.FenZhongZhangFu5
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuJia1() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia1
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuLiang1() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang1
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuJia2() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia2
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuLiang2() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang2
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuJia3() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia3
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuLiang3() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang3
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuJia4() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia4
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuLiang4() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang4
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuJia5() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia5
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuLiang5() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang5
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuJia1() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia1
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuLiang1() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang1
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuJia2() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia2
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuLiang2() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang2
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuJia3() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia3
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuLiang3() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang3
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuJia4() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia4
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuLiang4() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang4
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuJia5() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia5
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuLiang5() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang5
	}
	return 0
}

func (m *GeGuDongTai) GetWeiBi() YFloat {
	if m != nil {
		return m.WeiBi
	}
	return 0
}

func (m *GeGuDongTai) GetWeiCha() YFloat {
	if m != nil {
		return m.WeiCha
	}
	return 0
}

func (m *GeGuDongTai) GetJiaQuanPingJunWeiTuoMaiRuJia() YFloat {
	if m != nil {
		return m.JiaQuanPingJunWeiTuoMaiRuJia
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiRuZongLiang() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuZongLiang
	}
	return 0
}

func (m *GeGuDongTai) GetJiaQuanPingJunWeiTuoMaiChuJia() YFloat {
	if m != nil {
		return m.JiaQuanPingJunWeiTuoMaiChuJia
	}
	return 0
}

func (m *GeGuDongTai) GetWeiTuoMaiChuZongLiang() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuZongLiang
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuJia1() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia1
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuJia2() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia2
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuJia3() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia3
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuJia4() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia4
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuJia5() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia5
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuLiang1() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang1
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuLiang2() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang2
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuLiang3() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang3
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuLiang4() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang4
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiRuLiang5() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang5
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuJia1() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia1
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuJia2() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia2
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuJia3() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia3
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuJia4() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia4
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuJia5() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia5
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuLiang1() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang1
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuLiang2() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang2
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuLiang3() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang3
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuLiang4() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang4
	}
	return 0
}

func (m *GeGuDongTai) GetKuoZhanMaiChuLiang5() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang5
	}
	return 0
}

func (m *GeGuDongTai) GetChiCang() YFloat {
	if m != nil {
		return m.ChiCang
	}
	return 0
}

func (m *GeGuDongTai) GetZengCang() YFloat {
	if m != nil {
		return m.ZengCang
	}
	return 0
}

func (m *GeGuDongTai) GetRiZeng() YFloat {
	if m != nil {
		return m.RiZeng
	}
	return 0
}

func (m *GeGuDongTai) GetJieSuanJia() YFloat {
	if m != nil {
		return m.JieSuanJia
	}
	return 0
}

func (m *GeGuDongTai) GetZuoRiJieSuanJia() YFloat {
	if m != nil {
		return m.ZuoRiJieSuanJia
	}
	return 0
}

func (m *GeGuDongTai) GetKaiPing() YFloat {
	if m != nil {
		return m.KaiPing
	}
	return 0
}

func (m *GeGuDongTai) GetJieSuanZhangDie() YFloat {
	if m != nil {
		return m.JieSuanZhangDie
	}
	return 0
}

func (m *GeGuDongTai) GetJieSuanZhangFu() YFloat {
	if m != nil {
		return m.JieSuanZhangFu
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu1() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu1
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu2() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu2
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu3() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu3
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu4() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu4
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu5() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu5
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu6() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu6
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu7() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu7
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu8() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu8
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu9() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu9
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiRu10() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiRu10
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu1() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu1
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu2() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu2
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu3() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu3
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu4() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu4
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu5() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu5
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu6() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu6
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu7() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu7
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu8() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu8
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu9() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu9
	}
	return 0
}

func (m *GeGuDongTai) GetPanKouBianHuaMaiChu10() YFloat {
	if m != nil {
		return m.PanKouBianHuaMaiChu10
	}
	return 0
}

type MaiMaiPan struct {
	Id      YFloat `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	ShiJian YFloat `protobuf:"varint,2,opt,name=ShiJian" json:"ShiJian,omitempty"`
	// 5档委托盘
	WeiTuoMaiRuJia1    YFloat `protobuf:"varint,3,opt,name=WeiTuoMaiRuJia1" json:"WeiTuoMaiRuJia1,omitempty"`
	WeiTuoMaiRuLiang1  YFloat `protobuf:"varint,4,opt,name=WeiTuoMaiRuLiang1" json:"WeiTuoMaiRuLiang1,omitempty"`
	WeiTuoMaiRuJia2    YFloat `protobuf:"varint,5,opt,name=WeiTuoMaiRuJia2" json:"WeiTuoMaiRuJia2,omitempty"`
	WeiTuoMaiRuLiang2  YFloat `protobuf:"varint,6,opt,name=WeiTuoMaiRuLiang2" json:"WeiTuoMaiRuLiang2,omitempty"`
	WeiTuoMaiRuJia3    YFloat `protobuf:"varint,7,opt,name=WeiTuoMaiRuJia3" json:"WeiTuoMaiRuJia3,omitempty"`
	WeiTuoMaiRuLiang3  YFloat `protobuf:"varint,8,opt,name=WeiTuoMaiRuLiang3" json:"WeiTuoMaiRuLiang3,omitempty"`
	WeiTuoMaiRuJia4    YFloat `protobuf:"varint,9,opt,name=WeiTuoMaiRuJia4" json:"WeiTuoMaiRuJia4,omitempty"`
	WeiTuoMaiRuLiang4  YFloat `protobuf:"varint,10,opt,name=WeiTuoMaiRuLiang4" json:"WeiTuoMaiRuLiang4,omitempty"`
	WeiTuoMaiRuJia5    YFloat `protobuf:"varint,11,opt,name=WeiTuoMaiRuJia5" json:"WeiTuoMaiRuJia5,omitempty"`
	WeiTuoMaiRuLiang5  YFloat `protobuf:"varint,12,opt,name=WeiTuoMaiRuLiang5" json:"WeiTuoMaiRuLiang5,omitempty"`
	WeiTuoMaiChuJia1   YFloat `protobuf:"varint,13,opt,name=WeiTuoMaiChuJia1" json:"WeiTuoMaiChuJia1,omitempty"`
	WeiTuoMaiChuLiang1 YFloat `protobuf:"varint,14,opt,name=WeiTuoMaiChuLiang1" json:"WeiTuoMaiChuLiang1,omitempty"`
	WeiTuoMaiChuJia2   YFloat `protobuf:"varint,15,opt,name=WeiTuoMaiChuJia2" json:"WeiTuoMaiChuJia2,omitempty"`
	WeiTuoMaiChuLiang2 YFloat `protobuf:"varint,16,opt,name=WeiTuoMaiChuLiang2" json:"WeiTuoMaiChuLiang2,omitempty"`
	WeiTuoMaiChuJia3   YFloat `protobuf:"varint,17,opt,name=WeiTuoMaiChuJia3" json:"WeiTuoMaiChuJia3,omitempty"`
	WeiTuoMaiChuLiang3 YFloat `protobuf:"varint,18,opt,name=WeiTuoMaiChuLiang3" json:"WeiTuoMaiChuLiang3,omitempty"`
	WeiTuoMaiChuJia4   YFloat `protobuf:"varint,19,opt,name=WeiTuoMaiChuJia4" json:"WeiTuoMaiChuJia4,omitempty"`
	WeiTuoMaiChuLiang4 YFloat `protobuf:"varint,20,opt,name=WeiTuoMaiChuLiang4" json:"WeiTuoMaiChuLiang4,omitempty"`
	WeiTuoMaiChuJia5   YFloat `protobuf:"varint,21,opt,name=WeiTuoMaiChuJia5" json:"WeiTuoMaiChuJia5,omitempty"`
	WeiTuoMaiChuLiang5 YFloat `protobuf:"varint,22,opt,name=WeiTuoMaiChuLiang5" json:"WeiTuoMaiChuLiang5,omitempty"`
	WeiBi              YFloat `protobuf:"varint,23,opt,name=WeiBi" json:"WeiBi,omitempty"`
	WeiCha             YFloat `protobuf:"varint,24,opt,name=WeiCha" json:"WeiCha,omitempty"`
}

func (m *MaiMaiPan) Reset()                    { *m = MaiMaiPan{} }
func (m *MaiMaiPan) String() string            { return proto.CompactTextString(m) }
func (*MaiMaiPan) ProtoMessage()               {}
func (*MaiMaiPan) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *MaiMaiPan) GetId() YFloat {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MaiMaiPan) GetShiJian() YFloat {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuJia1() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia1
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuLiang1() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang1
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuJia2() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia2
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuLiang2() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang2
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuJia3() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia3
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuLiang3() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang3
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuJia4() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia4
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuLiang4() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang4
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuJia5() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuJia5
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiRuLiang5() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuLiang5
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuJia1() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia1
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuLiang1() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang1
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuJia2() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia2
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuLiang2() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang2
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuJia3() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia3
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuLiang3() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang3
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuJia4() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia4
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuLiang4() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang4
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuJia5() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuJia5
	}
	return 0
}

func (m *MaiMaiPan) GetWeiTuoMaiChuLiang5() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuLiang5
	}
	return 0
}

func (m *MaiMaiPan) GetWeiBi() YFloat {
	if m != nil {
		return m.WeiBi
	}
	return 0
}

func (m *MaiMaiPan) GetWeiCha() YFloat {
	if m != nil {
		return m.WeiCha
	}
	return 0
}

type KuoZhanMaiMaiPan struct {
	Id                            YFloat `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	ShiJian                       YFloat `protobuf:"varint,2,opt,name=ShiJian" json:"ShiJian,omitempty"`
	JiaQuanPingJunWeiTuoMaiRuJia  YFloat `protobuf:"varint,3,opt,name=JiaQuanPingJunWeiTuoMaiRuJia" json:"JiaQuanPingJunWeiTuoMaiRuJia,omitempty"`
	WeiTuoMaiRuZongLiang          YFloat `protobuf:"varint,4,opt,name=WeiTuoMaiRuZongLiang" json:"WeiTuoMaiRuZongLiang,omitempty"`
	JiaQuanPingJunWeiTuoMaiChuJia YFloat `protobuf:"varint,5,opt,name=JiaQuanPingJunWeiTuoMaiChuJia" json:"JiaQuanPingJunWeiTuoMaiChuJia,omitempty"`
	WeiTuoMaiChuZongLiang         YFloat `protobuf:"varint,6,opt,name=WeiTuoMaiChuZongLiang" json:"WeiTuoMaiChuZongLiang,omitempty"`
	KuoZhanMaiRuJia1              YFloat `protobuf:"varint,7,opt,name=KuoZhanMaiRuJia1" json:"KuoZhanMaiRuJia1,omitempty"`
	KuoZhanMaiRuJia2              YFloat `protobuf:"varint,8,opt,name=KuoZhanMaiRuJia2" json:"KuoZhanMaiRuJia2,omitempty"`
	KuoZhanMaiRuJia3              YFloat `protobuf:"varint,9,opt,name=KuoZhanMaiRuJia3" json:"KuoZhanMaiRuJia3,omitempty"`
	KuoZhanMaiRuJia4              YFloat `protobuf:"varint,10,opt,name=KuoZhanMaiRuJia4" json:"KuoZhanMaiRuJia4,omitempty"`
	KuoZhanMaiRuJia5              YFloat `protobuf:"varint,11,opt,name=KuoZhanMaiRuJia5" json:"KuoZhanMaiRuJia5,omitempty"`
	KuoZhanMaiRuLiang1            YFloat `protobuf:"varint,12,opt,name=KuoZhanMaiRuLiang1" json:"KuoZhanMaiRuLiang1,omitempty"`
	KuoZhanMaiRuLiang2            YFloat `protobuf:"varint,13,opt,name=KuoZhanMaiRuLiang2" json:"KuoZhanMaiRuLiang2,omitempty"`
	KuoZhanMaiRuLiang3            YFloat `protobuf:"varint,14,opt,name=KuoZhanMaiRuLiang3" json:"KuoZhanMaiRuLiang3,omitempty"`
	KuoZhanMaiRuLiang4            YFloat `protobuf:"varint,15,opt,name=KuoZhanMaiRuLiang4" json:"KuoZhanMaiRuLiang4,omitempty"`
	KuoZhanMaiRuLiang5            YFloat `protobuf:"varint,16,opt,name=KuoZhanMaiRuLiang5" json:"KuoZhanMaiRuLiang5,omitempty"`
	KuoZhanMaiChuJia1             YFloat `protobuf:"varint,17,opt,name=KuoZhanMaiChuJia1" json:"KuoZhanMaiChuJia1,omitempty"`
	KuoZhanMaiChuJia2             YFloat `protobuf:"varint,18,opt,name=KuoZhanMaiChuJia2" json:"KuoZhanMaiChuJia2,omitempty"`
	KuoZhanMaiChuJia3             YFloat `protobuf:"varint,19,opt,name=KuoZhanMaiChuJia3" json:"KuoZhanMaiChuJia3,omitempty"`
	KuoZhanMaiChuJia4             YFloat `protobuf:"varint,20,opt,name=KuoZhanMaiChuJia4" json:"KuoZhanMaiChuJia4,omitempty"`
	KuoZhanMaiChuJia5             YFloat `protobuf:"varint,21,opt,name=KuoZhanMaiChuJia5" json:"KuoZhanMaiChuJia5,omitempty"`
	KuoZhanMaiChuLiang1           YFloat `protobuf:"varint,22,opt,name=KuoZhanMaiChuLiang1" json:"KuoZhanMaiChuLiang1,omitempty"`
	KuoZhanMaiChuLiang2           YFloat `protobuf:"varint,23,opt,name=KuoZhanMaiChuLiang2" json:"KuoZhanMaiChuLiang2,omitempty"`
	KuoZhanMaiChuLiang3           YFloat `protobuf:"varint,24,opt,name=KuoZhanMaiChuLiang3" json:"KuoZhanMaiChuLiang3,omitempty"`
	KuoZhanMaiChuLiang4           YFloat `protobuf:"varint,25,opt,name=KuoZhanMaiChuLiang4" json:"KuoZhanMaiChuLiang4,omitempty"`
	KuoZhanMaiChuLiang5           YFloat `protobuf:"varint,26,opt,name=KuoZhanMaiChuLiang5" json:"KuoZhanMaiChuLiang5,omitempty"`
}

func (m *KuoZhanMaiMaiPan) Reset()                    { *m = KuoZhanMaiMaiPan{} }
func (m *KuoZhanMaiMaiPan) String() string            { return proto.CompactTextString(m) }
func (*KuoZhanMaiMaiPan) ProtoMessage()               {}
func (*KuoZhanMaiMaiPan) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *KuoZhanMaiMaiPan) GetId() YFloat {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetShiJian() YFloat {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetJiaQuanPingJunWeiTuoMaiRuJia() YFloat {
	if m != nil {
		return m.JiaQuanPingJunWeiTuoMaiRuJia
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetWeiTuoMaiRuZongLiang() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuZongLiang
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetJiaQuanPingJunWeiTuoMaiChuJia() YFloat {
	if m != nil {
		return m.JiaQuanPingJunWeiTuoMaiChuJia
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetWeiTuoMaiChuZongLiang() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuZongLiang
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuJia1() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia1
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuJia2() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia2
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuJia3() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia3
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuJia4() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia4
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuJia5() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuJia5
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuLiang1() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang1
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuLiang2() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang2
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuLiang3() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang3
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuLiang4() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang4
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiRuLiang5() YFloat {
	if m != nil {
		return m.KuoZhanMaiRuLiang5
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuJia1() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia1
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuJia2() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia2
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuJia3() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia3
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuJia4() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia4
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuJia5() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuJia5
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuLiang1() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang1
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuLiang2() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang2
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuLiang3() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang3
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuLiang4() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang4
	}
	return 0
}

func (m *KuoZhanMaiMaiPan) GetKuoZhanMaiChuLiang5() YFloat {
	if m != nil {
		return m.KuoZhanMaiChuLiang5
	}
	return 0
}

type QuanMaiMaiPan struct {
	Id           YFloat                       `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	ShiJian      YFloat                       `protobuf:"varint,2,opt,name=ShiJian" json:"ShiJian,omitempty"`
	WeiMaiRuPan  []*QuanMaiMaiPan_MaiMaiBiao `protobuf:"bytes,3,rep,name=WeiMaiRuPan" json:"WeiMaiRuPan,omitempty"`
	WeiMaiChuPan []*QuanMaiMaiPan_MaiMaiBiao `protobuf:"bytes,4,rep,name=WeiMaiChuPan" json:"WeiMaiChuPan,omitempty"`
}

func (m *QuanMaiMaiPan) Reset()                    { *m = QuanMaiMaiPan{} }
func (m *QuanMaiMaiPan) String() string            { return proto.CompactTextString(m) }
func (*QuanMaiMaiPan) ProtoMessage()               {}
func (*QuanMaiMaiPan) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *QuanMaiMaiPan) GetId() YFloat {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QuanMaiMaiPan) GetShiJian() YFloat {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *QuanMaiMaiPan) GetWeiMaiRuPan() []*QuanMaiMaiPan_MaiMaiBiao {
	if m != nil {
		return m.WeiMaiRuPan
	}
	return nil
}

func (m *QuanMaiMaiPan) GetWeiMaiChuPan() []*QuanMaiMaiPan_MaiMaiBiao {
	if m != nil {
		return m.WeiMaiChuPan
	}
	return nil
}

type QuanMaiMaiPan_MaiMaiBiao struct {
	WeiZhi YFloat `protobuf:"varint,1,opt,name=WeiZhi" json:"WeiZhi,omitempty"`
	Jia    YFloat `protobuf:"varint,2,opt,name=Jia" json:"Jia,omitempty"`
	Liang  YFloat `protobuf:"varint,3,opt,name=Liang" json:"Liang,omitempty"`
	DanShu YFloat `protobuf:"varint,4,opt,name=DanShu" json:"DanShu,omitempty"`
}

func (m *QuanMaiMaiPan_MaiMaiBiao) Reset()                    { *m = QuanMaiMaiPan_MaiMaiBiao{} }
func (m *QuanMaiMaiPan_MaiMaiBiao) String() string            { return proto.CompactTextString(m) }
func (*QuanMaiMaiPan_MaiMaiBiao) ProtoMessage()               {}
func (*QuanMaiMaiPan_MaiMaiBiao) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4, 0} }

func (m *QuanMaiMaiPan_MaiMaiBiao) GetWeiZhi() YFloat {
	if m != nil {
		return m.WeiZhi
	}
	return 0
}

func (m *QuanMaiMaiPan_MaiMaiBiao) GetJia() YFloat {
	if m != nil {
		return m.Jia
	}
	return 0
}

func (m *QuanMaiMaiPan_MaiMaiBiao) GetLiang() YFloat {
	if m != nil {
		return m.Liang
	}
	return 0
}

func (m *QuanMaiMaiPan_MaiMaiBiao) GetDanShu() YFloat {
	if m != nil {
		return m.DanShu
	}
	return 0
}

type WeiTuoDuiLie struct {
	Obj          string                 `protobuf:"bytes,1,opt,name=Obj" json:"Obj,omitempty"`
	ShiJian      YFloat                  `protobuf:"varint,2,opt,name=ShiJian" json:"ShiJian,omitempty"`
	MaiRuDuiLie  []*WeiTuoDuiLie_WeiTuo `protobuf:"bytes,3,rep,name=MaiRuDuiLie" json:"MaiRuDuiLie,omitempty"`
	MaiChuDuiLie []*WeiTuoDuiLie_WeiTuo `protobuf:"bytes,4,rep,name=MaiChuDuiLie" json:"MaiChuDuiLie,omitempty"`
}

func (m *WeiTuoDuiLie) Reset()                    { *m = WeiTuoDuiLie{} }
func (m *WeiTuoDuiLie) String() string            { return proto.CompactTextString(m) }
func (*WeiTuoDuiLie) ProtoMessage()               {}
func (*WeiTuoDuiLie) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5} }

func (m *WeiTuoDuiLie) GetObj() string {
	if m != nil {
		return m.Obj
	}
	return ""
}

func (m *WeiTuoDuiLie) GetShiJian() YFloat {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *WeiTuoDuiLie) GetMaiRuDuiLie() []*WeiTuoDuiLie_WeiTuo {
	if m != nil {
		return m.MaiRuDuiLie
	}
	return nil
}

func (m *WeiTuoDuiLie) GetMaiChuDuiLie() []*WeiTuoDuiLie_WeiTuo {
	if m != nil {
		return m.MaiChuDuiLie
	}
	return nil
}

type WeiTuoDuiLie_WeiTuo struct {
	Jia       YFloat   `protobuf:"varint,1,opt,name=Jia" json:"Jia,omitempty"`
	BiShu     YFloat   `protobuf:"varint,2,opt,name=BiShu" json:"BiShu,omitempty"`
	Liang     []YFloat `protobuf:"varint,3,rep,packed,name=Liang" json:"Liang,omitempty"`
	ZongLiang YFloat   `protobuf:"varint,4,opt,name=ZongLiang" json:"ZongLiang,omitempty"`
}

func (m *WeiTuoDuiLie_WeiTuo) Reset()                    { *m = WeiTuoDuiLie_WeiTuo{} }
func (m *WeiTuoDuiLie_WeiTuo) String() string            { return proto.CompactTextString(m) }
func (*WeiTuoDuiLie_WeiTuo) ProtoMessage()               {}
func (*WeiTuoDuiLie_WeiTuo) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5, 0} }

func (m *WeiTuoDuiLie_WeiTuo) GetJia() YFloat {
	if m != nil {
		return m.Jia
	}
	return 0
}

func (m *WeiTuoDuiLie_WeiTuo) GetBiShu() YFloat {
	if m != nil {
		return m.BiShu
	}
	return 0
}

func (m *WeiTuoDuiLie_WeiTuo) GetLiang() []YFloat {
	if m != nil {
		return m.Liang
	}
	return nil
}

func (m *WeiTuoDuiLie_WeiTuo) GetZongLiang() YFloat {
	if m != nil {
		return m.ZongLiang
	}
	return 0
}

type Level2TongJi struct {
	Id                 YFloat `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	ShiJian            YFloat `protobuf:"varint,2,opt,name=ShiJian" json:"ShiJian,omitempty"`
	WeiTuoMaiRu        YFloat `protobuf:"varint,3,opt,name=WeiTuoMaiRu" json:"WeiTuoMaiRu,omitempty"`
	WeiTuoMaiChu       YFloat `protobuf:"varint,4,opt,name=WeiTuoMaiChu" json:"WeiTuoMaiChu,omitempty"`
	MaiRuZhongDanBiLi  YFloat `protobuf:"varint,5,opt,name=MaiRuZhongDanBiLi" json:"MaiRuZhongDanBiLi,omitempty"`
	MaiRuDaDanBiLi     YFloat `protobuf:"varint,6,opt,name=MaiRuDaDanBiLi" json:"MaiRuDaDanBiLi,omitempty"`
	MaiRuTeDaDanBiLi   YFloat `protobuf:"varint,7,opt,name=MaiRuTeDaDanBiLi" json:"MaiRuTeDaDanBiLi,omitempty"`
	MaiChuZhongDanBiLi YFloat `protobuf:"varint,8,opt,name=MaiChuZhongDanBiLi" json:"MaiChuZhongDanBiLi,omitempty"`
	MaiChuDaDanBiLi    YFloat `protobuf:"varint,9,opt,name=MaiChuDaDanBiLi" json:"MaiChuDaDanBiLi,omitempty"`
	MaiChuTeDaDanBiLi  YFloat `protobuf:"varint,10,opt,name=MaiChuTeDaDanBiLi" json:"MaiChuTeDaDanBiLi,omitempty"`
	DuanXianMaiRu      YFloat `protobuf:"varint,11,opt,name=DuanXianMaiRu" json:"DuanXianMaiRu,omitempty"`
	DuanXianMaiChu     YFloat `protobuf:"varint,12,opt,name=DuanXianMaiChu" json:"DuanXianMaiChu,omitempty"`
	DuanXianChiHuo     YFloat `protobuf:"varint,13,opt,name=DuanXianChiHuo" json:"DuanXianChiHuo,omitempty"`
	DuanXianTuHuo      YFloat `protobuf:"varint,14,opt,name=DuanXianTuHuo" json:"DuanXianTuHuo,omitempty"`
	ChengJiaoLiang     YFloat `protobuf:"varint,15,opt,name=ChengJiaoLiang" json:"ChengJiaoLiang,omitempty"`
	ChengJiaoE         YFloat `protobuf:"varint,16,opt,name=ChengJiaoE" json:"ChengJiaoE,omitempty"`
}

func (m *Level2TongJi) Reset()                    { *m = Level2TongJi{} }
func (m *Level2TongJi) String() string            { return proto.CompactTextString(m) }
func (*Level2TongJi) ProtoMessage()               {}
func (*Level2TongJi) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{6} }

func (m *Level2TongJi) GetId() YFloat {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Level2TongJi) GetShiJian() YFloat {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *Level2TongJi) GetWeiTuoMaiRu() YFloat {
	if m != nil {
		return m.WeiTuoMaiRu
	}
	return 0
}

func (m *Level2TongJi) GetWeiTuoMaiChu() YFloat {
	if m != nil {
		return m.WeiTuoMaiChu
	}
	return 0
}

func (m *Level2TongJi) GetMaiRuZhongDanBiLi() YFloat {
	if m != nil {
		return m.MaiRuZhongDanBiLi
	}
	return 0
}

func (m *Level2TongJi) GetMaiRuDaDanBiLi() YFloat {
	if m != nil {
		return m.MaiRuDaDanBiLi
	}
	return 0
}

func (m *Level2TongJi) GetMaiRuTeDaDanBiLi() YFloat {
	if m != nil {
		return m.MaiRuTeDaDanBiLi
	}
	return 0
}

func (m *Level2TongJi) GetMaiChuZhongDanBiLi() YFloat {
	if m != nil {
		return m.MaiChuZhongDanBiLi
	}
	return 0
}

func (m *Level2TongJi) GetMaiChuDaDanBiLi() YFloat {
	if m != nil {
		return m.MaiChuDaDanBiLi
	}
	return 0
}

func (m *Level2TongJi) GetMaiChuTeDaDanBiLi() YFloat {
	if m != nil {
		return m.MaiChuTeDaDanBiLi
	}
	return 0
}

func (m *Level2TongJi) GetDuanXianMaiRu() YFloat {
	if m != nil {
		return m.DuanXianMaiRu
	}
	return 0
}

func (m *Level2TongJi) GetDuanXianMaiChu() YFloat {
	if m != nil {
		return m.DuanXianMaiChu
	}
	return 0
}

func (m *Level2TongJi) GetDuanXianChiHuo() YFloat {
	if m != nil {
		return m.DuanXianChiHuo
	}
	return 0
}

func (m *Level2TongJi) GetDuanXianTuHuo() YFloat {
	if m != nil {
		return m.DuanXianTuHuo
	}
	return 0
}

func (m *Level2TongJi) GetChengJiaoLiang() YFloat {
	if m != nil {
		return m.ChengJiaoLiang
	}
	return 0
}

func (m *Level2TongJi) GetChengJiaoE() YFloat {
	if m != nil {
		return m.ChengJiaoE
	}
	return 0
}

type DynaMMP struct {
	Rows []*DynaMaiMaiPrice `protobuf:"bytes,1,rep,name=Rows" json:"Rows,omitempty"`
}

func (m *DynaMMP) Reset()                    { *m = DynaMMP{} }
func (m *DynaMMP) String() string            { return proto.CompactTextString(m) }
func (*DynaMMP) ProtoMessage()               {}
func (*DynaMMP) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{7} }

func (m *DynaMMP) GetRows() []*DynaMaiMaiPrice {
	if m != nil {
		return m.Rows
	}
	return nil
}

type DynaMaiMaiPrice struct {
	JiaGe  YFloat `protobuf:"varint,1,opt,name=JiaGe" json:"JiaGe,omitempty"`
	Liang  YFloat `protobuf:"varint,2,opt,name=Liang" json:"Liang,omitempty"`
	ChaZhi YFloat `protobuf:"varint,3,opt,name=ChaZhi" json:"ChaZhi,omitempty"`
}

func (m *DynaMaiMaiPrice) Reset()                    { *m = DynaMaiMaiPrice{} }
func (m *DynaMaiMaiPrice) String() string            { return proto.CompactTextString(m) }
func (*DynaMaiMaiPrice) ProtoMessage()               {}
func (*DynaMaiMaiPrice) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

func (m *DynaMaiMaiPrice) GetJiaGe() YFloat {
	if m != nil {
		return m.JiaGe
	}
	return 0
}

func (m *DynaMaiMaiPrice) GetLiang() YFloat {
	if m != nil {
		return m.Liang
	}
	return 0
}

func (m *DynaMaiMaiPrice) GetChaZhi() YFloat {
	if m != nil {
		return m.ChaZhi
	}
	return 0
}

type DynaMaiMaiZongLiang struct {
	ShiJian               YFloat `protobuf:"varint,1,opt,name=ShiJian" json:"ShiJian,omitempty"`
	WeiTuoMaiRuZongLiang  YFloat `protobuf:"varint,2,opt,name=WeiTuoMaiRuZongLiang" json:"WeiTuoMaiRuZongLiang,omitempty"`
	WeiTuoMaiChuZongLiang YFloat `protobuf:"varint,3,opt,name=WeiTuoMaiChuZongLiang" json:"WeiTuoMaiChuZongLiang,omitempty"`
}

func (m *DynaMaiMaiZongLiang) Reset()                    { *m = DynaMaiMaiZongLiang{} }
func (m *DynaMaiMaiZongLiang) String() string            { return proto.CompactTextString(m) }
func (*DynaMaiMaiZongLiang) ProtoMessage()               {}
func (*DynaMaiMaiZongLiang) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{9} }

func (m *DynaMaiMaiZongLiang) GetShiJian() YFloat {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *DynaMaiMaiZongLiang) GetWeiTuoMaiRuZongLiang() YFloat {
	if m != nil {
		return m.WeiTuoMaiRuZongLiang
	}
	return 0
}

func (m *DynaMaiMaiZongLiang) GetWeiTuoMaiChuZongLiang() YFloat {
	if m != nil {
		return m.WeiTuoMaiChuZongLiang
	}
	return 0
}

type DynaFenshiStatus struct {
	ShiJian     YFloat        `protobuf:"varint,1,opt,name=ShiJian" json:"ShiJian,omitempty"`
	IndexStatuc YFloat        `protobuf:"varint,2,opt,name=IndexStatuc" json:"IndexStatuc,omitempty"`
	DataStatus  *GeGuDongTai `protobuf:"bytes,3,opt,name=DataStatus" json:"DataStatus,omitempty"`
}

func (m *DynaFenshiStatus) Reset()                    { *m = DynaFenshiStatus{} }
func (m *DynaFenshiStatus) String() string            { return proto.CompactTextString(m) }
func (*DynaFenshiStatus) ProtoMessage()               {}
func (*DynaFenshiStatus) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{10} }

func (m *DynaFenshiStatus) GetShiJian() YFloat {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *DynaFenshiStatus) GetIndexStatuc() YFloat {
	if m != nil {
		return m.IndexStatuc
	}
	return 0
}

func (m *DynaFenshiStatus) GetDataStatus() *GeGuDongTai {
	if m != nil {
		return m.DataStatus
	}
	return nil
}

func init() {
	proto.RegisterType((*FenBiChengJiao)(nil), "dzhyun.FenBiChengJiao")
	proto.RegisterType((*GeGuDongTai)(nil), "dzhyun.GeGuDongTai")
	proto.RegisterType((*MaiMaiPan)(nil), "dzhyun.MaiMaiPan")
	proto.RegisterType((*KuoZhanMaiMaiPan)(nil), "dzhyun.KuoZhanMaiMaiPan")
	proto.RegisterType((*QuanMaiMaiPan)(nil), "dzhyun.QuanMaiMaiPan")
	proto.RegisterType((*QuanMaiMaiPan_MaiMaiBiao)(nil), "dzhyun.QuanMaiMaiPan.MaiMaiBiao")
	proto.RegisterType((*WeiTuoDuiLie)(nil), "dzhyun.WeiTuoDuiLie")
	proto.RegisterType((*WeiTuoDuiLie_WeiTuo)(nil), "dzhyun.WeiTuoDuiLie.WeiTuo")
	proto.RegisterType((*Level2TongJi)(nil), "dzhyun.Level2TongJi")
	proto.RegisterType((*DynaMMP)(nil), "dzhyun.DynaMMP")
	proto.RegisterType((*DynaMaiMaiPrice)(nil), "dzhyun.DynaMaiMaiPrice")
	proto.RegisterType((*DynaMaiMaiZongLiang)(nil), "dzhyun.DynaMaiMaiZongLiang")
	proto.RegisterType((*DynaFenshiStatus)(nil), "dzhyun.DynaFenshiStatus")
}

func init() { proto.RegisterFile("dzhyun.gupiaoqiepian.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 1971 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x5a, 0xdb, 0x7a, 0x1c, 0x47,
	0x11, 0xfe, 0xa4, 0xd5, 0xb1, 0x57, 0x27, 0x8f, 0x64, 0xa9, 0xa2, 0x38, 0x41, 0x2c, 0x21, 0x98,
	0x24, 0x08, 0x6b, 0x0e, 0x3a, 0x00, 0x21, 0xa0, 0x5d, 0xaf, 0xec, 0xb5, 0x94, 0x28, 0xbb, 0x1b,
	0x64, 0x96, 0x63, 0xdb, 0x1a, 0x76, 0x9a, 0x0f, 0x66, 0x4c, 0xac, 0x06, 0xc2, 0x2d, 0x4f, 0xc1,
	0x1d, 0xb7, 0xbc, 0x0b, 0xf7, 0xdc, 0x70, 0xcf, 0x0d, 0x0f, 0xc1, 0x57, 0xdd, 0x3d, 0x3b, 0x87,
	0xad, 0x96, 0xdd, 0xf8, 0xca, 0x5b, 0x55, 0xff, 0x5f, 0xd3, 0x5d, 0xdd, 0x53, 0xdd, 0xbf, 0x47,
	0x6c, 0xf7, 0xfa, 0x2f, 0xc9, 0x57, 0x32, 0xdd, 0x1f, 0xcb, 0x17, 0x82, 0x67, 0x7f, 0x10, 0xf1,
	0x0b, 0xc1, 0xd3, 0xfd, 0x17, 0x5f, 0x66, 0x37, 0x99, 0xb7, 0xa0, 0x63, 0xad, 0x7f, 0x36, 0xd8,
	0x5a, 0x37, 0x4e, 0x4f, 0x45, 0x3b, 0x89, 0xd3, 0x71, 0x4f, 0xf0, 0xcc, 0x5b, 0x63, 0xb3, 0x8f,
	0xaf, 0x61, 0x66, 0x6f, 0xe6, 0x7e, 0xa3, 0x3f, 0xfb, 0xf8, 0xda, 0x03, 0xb6, 0x38, 0x48, 0x44,
	0x4f, 0xf0, 0x14, 0x66, 0x95, 0x33, 0x37, 0xbd, 0x16, 0x5b, 0x99, 0xd0, 0x7a, 0x82, 0x43, 0x43,
	0x85, 0x2b, 0x3e, 0xef, 0x7d, 0xb6, 0x36, 0xb1, 0xcf, 0x05, 0x4f, 0xc7, 0x30, 0xa7, 0x50, 0x35,
	0xaf, 0xf7, 0x2e, 0x63, 0x13, 0xcf, 0x43, 0x98, 0x57, 0x98, 0x92, 0xc7, 0xfb, 0x88, 0xdd, 0x99,
	0x58, 0x1d, 0x9e, 0x9e, 0x8a, 0x41, 0x22, 0x61, 0x41, 0xc1, 0xa6, 0x03, 0xde, 0x31, 0xdb, 0x19,
	0x24, 0xa2, 0x9b, 0xc9, 0x51, 0x22, 0x3b, 0x59, 0x3a, 0x7e, 0x2a, 0xd2, 0xf1, 0x05, 0x17, 0x1d,
	0x9e, 0xc2, 0xa2, 0xe2, 0xd8, 0xc2, 0xde, 0x7d, 0xb6, 0x7e, 0xc1, 0xc5, 0x05, 0x17, 0x5d, 0x8e,
	0x7e, 0x1c, 0xf0, 0x92, 0x62, 0xd4, 0xdd, 0xde, 0x03, 0xb6, 0xd9, 0xe1, 0x69, 0x5b, 0xd4, 0xa6,
	0xb7, 0xac, 0xd0, 0x54, 0x08, 0x73, 0x57, 0xdd, 0x0f, 0x81, 0xe9, 0xdc, 0x35, 0xb7, 0x77, 0xc8,
	0xb6, 0xab, 0xae, 0xc9, 0x94, 0x9b, 0x8a, 0x60, 0x89, 0xb6, 0xfe, 0xd5, 0x62, 0xcd, 0xb3, 0xf8,
	0x4c, 0x4d, 0x6a, 0xc8, 0x85, 0xc3, 0x5a, 0xde, 0x63, 0xcb, 0x23, 0x29, 0x9e, 0x8a, 0xb4, 0x58,
	0xc8, 0xc2, 0x81, 0xd1, 0x27, 0x5c, 0x5c, 0x72, 0x15, 0xd5, 0x0b, 0x58, 0x38, 0x0c, 0xf7, 0x4c,
	0x6f, 0x82, 0xf9, 0x09, 0x57, 0x3b, 0xbc, 0x5d, 0xb6, 0x34, 0x92, 0xa2, 0x83, 0x8f, 0x31, 0x0b,
	0x36, 0xb1, 0x71, 0x3c, 0x23, 0x99, 0x0d, 0x92, 0x4c, 0x9a, 0x75, 0xc9, 0x4d, 0x6f, 0x9b, 0x2d,
	0xf4, 0xa4, 0x7a, 0x9c, 0x2e, 0xbf, 0xb1, 0x54, 0xb6, 0x84, 0xa7, 0xe3, 0x8e, 0x88, 0x4d, 0xa9,
	0x27, 0xb6, 0xca, 0x86, 0xbf, 0xbb, 0xd2, 0xd4, 0x35, 0x37, 0x31, 0xdb, 0x28, 0x89, 0xd3, 0x6e,
	0x5e, 0x3f, 0x63, 0x11, 0xbb, 0x73, 0x85, 0xdc, 0x9d, 0xbb, 0x6c, 0x09, 0x17, 0x5d, 0x0d, 0x74,
	0x55, 0x3f, 0x35, 0xb7, 0x6b, 0x3b, 0x77, 0x6d, 0x6a, 0xe7, 0xee, 0x33, 0x6f, 0x94, 0xa5, 0xe3,
	0x89, 0x47, 0xaf, 0xe3, 0xba, 0xc2, 0x11, 0x11, 0xdc, 0x57, 0x17, 0xb1, 0x28, 0xbd, 0x91, 0x67,
	0x12, 0x09, 0x1b, 0x7a, 0x5f, 0x11, 0x21, 0x1c, 0xdd, 0x23, 0x69, 0x46, 0x77, 0x47, 0x8f, 0x2e,
	0xb7, 0xb1, 0x26, 0x6a, 0x0a, 0xa7, 0x02, 0x3c, 0x5d, 0x13, 0x63, 0x62, 0x4d, 0x3e, 0x8d, 0x71,
	0x09, 0x61, 0x53, 0xd7, 0x44, 0x5b, 0xe8, 0xbf, 0x52, 0x4b, 0x0b, 0x5b, 0xda, 0xaf, 0x2d, 0xb5,
	0xca, 0x99, 0x7a, 0x4f, 0xfa, 0x12, 0xee, 0x9a, 0x55, 0xce, 0x1d, 0x58, 0x05, 0x63, 0xb4, 0x13,
	0x09, 0xdb, 0xba, 0x0a, 0x85, 0x07, 0xf7, 0xfe, 0x04, 0x6c, 0x16, 0x76, 0x47, 0xef, 0xfd, 0x9a,
	0xdb, 0xfb, 0x80, 0x6d, 0x14, 0x3c, 0x03, 0x05, 0x05, 0x9d, 0xf2, 0xab, 0x31, 0xe1, 0x12, 0x0f,
	0x45, 0x3a, 0x86, 0xb7, 0xcc, 0x98, 0x72, 0x07, 0xce, 0xbd, 0x23, 0x62, 0x15, 0xdb, 0xd5, 0x73,
	0x37, 0x26, 0x3e, 0xa3, 0x1b, 0xa7, 0xa3, 0x24, 0x4b, 0xc7, 0x66, 0x8b, 0x1c, 0xc0, 0xdb, 0xfa,
	0x19, 0x75, 0x3f, 0x81, 0xf5, 0xe1, 0x1e, 0x89, 0xf5, 0x09, 0x6c, 0x00, 0xef, 0x90, 0xd8, 0x80,
	0xc0, 0x86, 0xf0, 0x2e, 0x89, 0x0d, 0x09, 0x6c, 0x04, 0x5f, 0x23, 0xb1, 0x11, 0x56, 0xfa, 0x2a,
	0x16, 0x43, 0x99, 0xe9, 0xa2, 0x0a, 0x7e, 0x00, 0x7b, 0xba, 0xd2, 0x35, 0x37, 0xf6, 0xd4, 0x92,
	0x4b, 0xed, 0x8b, 0x03, 0xf8, 0xba, 0xee, 0xa9, 0x53, 0x81, 0xe9, 0xbc, 0x3e, 0xb4, 0xa8, 0xbc,
	0x3e, 0x95, 0xd7, 0x87, 0x6f, 0xd0, 0x79, 0xfd, 0xe9, 0xbc, 0x01, 0xbc, 0x47, 0xe5, 0x0d, 0xa8,
	0xbc, 0x01, 0x7c, 0x93, 0xce, 0x1b, 0x4c, 0xe7, 0x0d, 0xe1, 0x7d, 0x2a, 0x6f, 0x48, 0xe5, 0x0d,
	0xe1, 0x5b, 0x74, 0xde, 0x70, 0x3a, 0x6f, 0x04, 0xf7, 0xa9, 0xbc, 0x11, 0x95, 0x37, 0x82, 0x6f,
	0xd3, 0x79, 0x23, 0x5c, 0xe3, 0x89, 0x13, 0x77, 0x38, 0x2e, 0xdc, 0x07, 0x7a, 0x8d, 0xeb, 0x7e,
	0xec, 0x29, 0x65, 0x9f, 0x59, 0xba, 0x0f, 0x75, 0x4f, 0x99, 0x8e, 0x10, 0xb9, 0x7d, 0xf8, 0x88,
	0xcc, 0xed, 0x93, 0xb9, 0x7d, 0xf8, 0x8e, 0x25, 0xb7, 0x4f, 0xe4, 0x0e, 0x60, 0x9f, 0xcc, 0x1d,
	0x90, 0xb9, 0x03, 0xf8, 0xae, 0x25, 0x77, 0x40, 0xe4, 0x0e, 0xe1, 0x01, 0x99, 0x3b, 0x24, 0x73,
	0x87, 0x70, 0x60, 0xc9, 0x1d, 0x12, 0xb9, 0x23, 0xf0, 0xc9, 0xdc, 0x11, 0x99, 0x3b, 0x82, 0xc0,
	0x92, 0x3b, 0xf2, 0xb6, 0xd8, 0xfc, 0x15, 0x36, 0x6a, 0x08, 0x15, 0x44, 0x1b, 0xaa, 0xb3, 0xc6,
	0xa2, 0x9d, 0x70, 0x88, 0x4c, 0x67, 0x55, 0x96, 0x77, 0xca, 0xee, 0xf5, 0x04, 0xff, 0x5c, 0xf2,
	0xf4, 0x52, 0xa4, 0xe3, 0x9e, 0x4c, 0xab, 0x1b, 0x09, 0x0e, 0x15, 0xfa, 0x56, 0x8c, 0xe7, 0xb3,
	0xad, 0x92, 0x07, 0x1b, 0xa5, 0x3e, 0xcf, 0x8e, 0x14, 0x97, 0x8c, 0x79, 0x1d, 0xf6, 0x8e, 0x25,
	0xa7, 0x9e, 0x37, 0x1c, 0x2b, 0xf2, 0xed, 0x20, 0x2f, 0x64, 0x77, 0xcb, 0xae, 0xe2, 0xd1, 0x27,
	0x8a, 0x4d, 0x07, 0xb1, 0xfa, 0x4f, 0x64, 0x86, 0x4d, 0xab, 0x68, 0x53, 0xdf, 0xd3, 0xd5, 0xaf,
	0xfb, 0x09, 0xac, 0x0f, 0xdf, 0x27, 0xb1, 0x3e, 0x81, 0x0d, 0xe0, 0x07, 0x24, 0x36, 0x20, 0xb0,
	0x21, 0x7c, 0x4c, 0x62, 0x43, 0x02, 0x1b, 0xc1, 0x0f, 0x49, 0xac, 0xda, 0x2d, 0x65, 0x9f, 0x79,
	0x3b, 0x3f, 0xd1, 0xbb, 0x65, 0x3a, 0x42, 0xe2, 0x7d, 0xf8, 0x91, 0x05, 0xef, 0x93, 0xf8, 0x00,
	0x7e, 0x6c, 0xc1, 0x07, 0x24, 0x3e, 0x84, 0x53, 0x0b, 0x3e, 0x24, 0xf1, 0x11, 0xb4, 0x2d, 0x78,
	0xd5, 0xe7, 0x0a, 0x6f, 0xde, 0xba, 0x3a, 0xba, 0xcf, 0x4d, 0x05, 0x28, 0xb4, 0x0f, 0x0f, 0x69,
	0xb4, 0x4f, 0xa1, 0x03, 0xe8, 0xd2, 0xe8, 0x80, 0x42, 0x87, 0x70, 0x46, 0xa3, 0x43, 0x0a, 0x1d,
	0xc1, 0x23, 0x1a, 0x1d, 0xe1, 0xbd, 0xac, 0xe2, 0x34, 0xcb, 0xfa, 0x58, 0xdf, 0xcb, 0x88, 0x10,
	0xcd, 0xf0, 0xa1, 0x67, 0x63, 0xf8, 0x34, 0x23, 0x80, 0x27, 0x36, 0x46, 0x40, 0x33, 0x42, 0x38,
	0xb7, 0x31, 0x42, 0x9a, 0x11, 0xc1, 0x85, 0x8d, 0x11, 0xe1, 0x3d, 0xaa, 0x9d, 0x88, 0x36, 0xbe,
	0xd3, 0x9f, 0xea, 0x7b, 0x94, 0x31, 0xd5, 0x6d, 0x3c, 0x4e, 0xc7, 0x2a, 0xf4, 0x99, 0xb9, 0x8d,
	0x1b, 0x1b, 0xbb, 0x5d, 0x5f, 0xa0, 0x05, 0x97, 0xba, 0xdb, 0x69, 0x0b, 0x6f, 0x8a, 0x3d, 0x11,
	0x0f, 0xa4, 0x16, 0x13, 0x9f, 0xeb, 0x9b, 0x62, 0xe1, 0x51, 0x37, 0x45, 0x99, 0xf5, 0x45, 0x09,
	0xd4, 0x37, 0x37, 0xc5, 0xaa, 0x1b, 0xc7, 0x85, 0x22, 0x04, 0xef, 0x77, 0x03, 0x3d, 0x2e, 0x63,
	0x62, 0x0e, 0x83, 0x9b, 0x88, 0x85, 0xa1, 0xce, 0x51, 0x73, 0xa3, 0x02, 0x28, 0xbb, 0xba, 0x12,
	0xbe, 0xd0, 0x0a, 0xa0, 0xea, 0xc5, 0xaa, 0x5d, 0xf2, 0xf4, 0x49, 0x26, 0x4f, 0x05, 0x4f, 0x1f,
	0x49, 0xae, 0xf6, 0xff, 0x01, 0xfc, 0x44, 0x57, 0x8d, 0x08, 0xd1, 0x0c, 0x1f, 0xae, 0x6c, 0x0c,
	0x9f, 0x66, 0x04, 0xf0, 0xd4, 0xc6, 0x08, 0x68, 0x46, 0x08, 0x3f, 0xb5, 0x31, 0x42, 0x9a, 0x11,
	0xc1, 0xc8, 0xc6, 0x88, 0x68, 0xc6, 0x21, 0xfc, 0xcc, 0xc6, 0x38, 0xa4, 0x19, 0x47, 0xf0, 0x73,
	0x1b, 0xe3, 0x88, 0x66, 0x1c, 0xc3, 0x2f, 0x6c, 0x8c, 0x63, 0x9a, 0x71, 0x02, 0xbf, 0xb4, 0x31,
	0x4e, 0xf0, 0x84, 0x24, 0x96, 0xe9, 0x01, 0xfc, 0x4a, 0x9f, 0x90, 0x54, 0x8c, 0xe2, 0xb4, 0x13,
	0x79, 0x00, 0xbf, 0xa6, 0x39, 0x18, 0xb3, 0x70, 0x7c, 0xe0, 0x56, 0x8e, 0x6f, 0xe1, 0x04, 0xf0,
	0xcc, 0xca, 0x09, 0x2c, 0x9c, 0x10, 0x9e, 0x5b, 0x39, 0xa1, 0x85, 0x13, 0xc1, 0xb5, 0x95, 0x13,
	0x59, 0x38, 0x87, 0x10, 0x5b, 0x39, 0x87, 0x16, 0xce, 0x11, 0xfc, 0xc6, 0xca, 0x39, 0xb2, 0x70,
	0x8e, 0x61, 0x6c, 0xe5, 0x1c, 0x5b, 0x38, 0x27, 0x90, 0x58, 0x39, 0x27, 0x78, 0x5f, 0xa1, 0xd6,
	0xed, 0x01, 0x08, 0x7d, 0x5f, 0x21, 0x83, 0xad, 0xff, 0x2c, 0xb2, 0x65, 0xfd, 0x3f, 0x40, 0xa8,
	0x85, 0x5f, 0xff, 0xff, 0x55, 0x08, 0x35, 0xd6, 0x70, 0x50, 0x63, 0x73, 0x0e, 0x6a, 0x6c, 0xde,
	0x41, 0x8d, 0x2d, 0x38, 0xa8, 0xb1, 0x45, 0x07, 0x35, 0xb6, 0xe4, 0xa0, 0xc6, 0x96, 0x1d, 0xd4,
	0x18, 0x73, 0x50, 0x63, 0x4d, 0x07, 0x35, 0xb6, 0xe2, 0xa2, 0xc6, 0x56, 0x9d, 0xd4, 0xd8, 0x9a,
	0x93, 0x1a, 0x5b, 0x77, 0x52, 0x63, 0x1b, 0x4e, 0x6a, 0xec, 0x8e, 0x93, 0x1a, 0xf3, 0x9c, 0xd4,
	0xd8, 0xa6, 0x93, 0x1a, 0xdb, 0x72, 0x52, 0x63, 0x77, 0x9d, 0xd4, 0xd8, 0xf6, 0xab, 0xd5, 0xd8,
	0x0e, 0xad, 0xc6, 0xa0, 0xac, 0xc6, 0x5a, 0xff, 0x5e, 0x2e, 0x5f, 0xf5, 0x9d, 0x5f, 0xf8, 0x57,
	0x89, 0xb9, 0xc6, 0x1b, 0x88, 0xb9, 0xb9, 0x37, 0x11, 0x73, 0xf3, 0x6f, 0x24, 0xe6, 0x16, 0x5c,
	0xc5, 0xdc, 0xa2, 0x83, 0x98, 0x5b, 0x72, 0x10, 0x73, 0xcb, 0x0e, 0x62, 0x8e, 0x39, 0x88, 0xb9,
	0xa6, 0x93, 0x98, 0x5b, 0x71, 0x14, 0x73, 0xab, 0x8e, 0x62, 0x6e, 0xcd, 0x51, 0xcc, 0xad, 0x3b,
	0x8a, 0xb9, 0x0d, 0x37, 0x31, 0x77, 0xc7, 0x49, 0xcc, 0x79, 0x4e, 0x62, 0x6e, 0xd3, 0x49, 0xcc,
	0x6d, 0x39, 0x89, 0xb9, 0xbb, 0x8e, 0x62, 0x6e, 0xdb, 0x59, 0xcc, 0xed, 0x38, 0x8b, 0x39, 0x70,
	0x16, 0x73, 0x6f, 0x39, 0x8b, 0xb9, 0x5d, 0xab, 0x98, 0x6b, 0xfd, 0x63, 0x96, 0xad, 0x62, 0x03,
	0xf8, 0xff, 0x7a, 0x5b, 0xf3, 0x2a, 0x16, 0x6a, 0xb7, 0x5c, 0xf2, 0x14, 0x1a, 0x7b, 0x8d, 0xfb,
	0x4d, 0x7f, 0x6f, 0xdf, 0x7c, 0x67, 0xac, 0x64, 0xdd, 0xd7, 0xbf, 0x4e, 0x05, 0xcf, 0xfa, 0x65,
	0x92, 0xd7, 0x61, 0x2b, 0xda, 0x6c, 0x27, 0x2a, 0xc9, 0xdc, 0x6b, 0x26, 0xa9, 0xb0, 0x76, 0xaf,
	0x19, 0x2b, 0x62, 0xa6, 0x95, 0x8f, 0x12, 0x61, 0x66, 0x61, 0x2c, 0x6f, 0x83, 0x35, 0xb0, 0xf3,
	0xe9, 0x59, 0xe0, 0x4f, 0x3c, 0x0a, 0x74, 0x3f, 0xd3, 0x6d, 0x58, 0x1b, 0xc8, 0xef, 0xf0, 0x74,
	0x90, 0x48, 0xd3, 0x61, 0x8d, 0xd5, 0xfa, 0xfb, 0xac, 0x1a, 0xec, 0x50, 0x66, 0x1d, 0x29, 0xce,
	0x45, 0x8c, 0x09, 0x3f, 0x7b, 0xf6, 0x5b, 0xf5, 0x94, 0xe5, 0x3e, 0xfe, 0xbc, 0xa5, 0x58, 0x1f,
	0xb3, 0xa6, 0x9a, 0xb4, 0xa6, 0x9a, 0x62, 0xbd, 0x9d, 0xcf, 0xb3, 0x9c, 0xd6, 0x18, 0xfd, 0x32,
	0xde, 0xfb, 0x84, 0xad, 0xe8, 0xe9, 0x1a, 0xfe, 0xdc, 0xab, 0xf9, 0x15, 0xc2, 0xee, 0xb5, 0x2a,
	0xca, 0x50, 0x66, 0x79, 0x19, 0x66, 0x2a, 0x65, 0xd0, 0x9f, 0xa1, 0xf4, 0x98, 0xb5, 0x51, 0x2e,
	0x4e, 0xa3, 0x28, 0x8e, 0xf9, 0xee, 0x53, 0x3e, 0x81, 0x0a, 0x47, 0xeb, 0xbf, 0x73, 0x6c, 0xe5,
	0x3c, 0xfe, 0x63, 0xfc, 0x3b, 0x7f, 0x98, 0xa5, 0xe3, 0x9e, 0xcb, 0x27, 0xc7, 0x3d, 0xb5, 0x9b,
	0xf2, 0x93, 0xcc, 0xac, 0x48, 0xd9, 0xe5, 0xb5, 0xf2, 0xf2, 0x9b, 0xcf, 0x4a, 0xfa, 0xe9, 0x15,
	0x1f, 0xbe, 0xf7, 0xfa, 0x24, 0x4c, 0xb2, 0x74, 0xac, 0x3e, 0x84, 0x9e, 0x0b, 0x73, 0xd6, 0x4d,
	0x07, 0x50, 0xee, 0xeb, 0x22, 0xf3, 0x1c, 0xaa, 0x0f, 0xb6, 0x9a, 0x17, 0x4f, 0x08, 0xe5, 0x19,
	0xc6, 0x05, 0xd2, 0x9c, 0x68, 0x75, 0x3f, 0x76, 0x58, 0x73, 0x20, 0x96, 0x87, 0xa0, 0xcf, 0x34,
	0x22, 0x62, 0x3e, 0x31, 0xe3, 0x42, 0x4d, 0x52, 0x2f, 0x4f, 0x3e, 0x31, 0x97, 0xdd, 0x66, 0x6e,
	0xed, 0xa4, 0x32, 0x0c, 0x36, 0x99, 0x5b, 0x35, 0xe0, 0xbd, 0xc7, 0x56, 0x3b, 0x92, 0xa7, 0x4f,
	0x85, 0x69, 0xe8, 0xe6, 0x48, 0xab, 0x3a, 0xb1, 0x02, 0x25, 0x07, 0x56, 0xd5, 0x7c, 0xf2, 0xac,
	0x7a, 0xcb, 0xb8, 0x76, 0x22, 0x1e, 0xc9, 0xcc, 0x9c, 0x61, 0x35, 0x6f, 0xf9, 0xa9, 0x43, 0x89,
	0xb0, 0xb5, 0xea, 0x53, 0x95, 0x93, 0xf8, 0xd0, 0xba, 0xfe, 0x1a, 0x7f, 0x06, 0xb0, 0x51, 0xff,
	0x98, 0xda, 0x3a, 0x64, 0x8b, 0x9d, 0xaf, 0x52, 0x7e, 0x71, 0x71, 0xe9, 0x7d, 0xc8, 0xe6, 0xfa,
	0xd9, 0x9f, 0x5e, 0xc2, 0x8c, 0x7a, 0x31, 0x76, 0xf2, 0x17, 0x43, 0x85, 0x75, 0x03, 0xf9, 0x52,
	0x3c, 0x8f, 0xfb, 0x0a, 0xd4, 0xfa, 0x82, 0xad, 0xd7, 0x02, 0xb8, 0xdb, 0x7b, 0x82, 0x9f, 0xc5,
	0x66, 0xaf, 0x6a, 0xa3, 0x78, 0x07, 0x66, 0x6b, 0x0d, 0xa2, 0x9d, 0x70, 0x6c, 0x30, 0x7a, 0x97,
	0x1a, 0xab, 0xf5, 0xb7, 0x19, 0xb6, 0x59, 0xe4, 0x2d, 0x2e, 0x44, 0xa5, 0x4d, 0x3f, 0x53, 0xdd,
	0xf4, 0xb6, 0xab, 0xdd, 0xec, 0x2d, 0x57, 0x3b, 0xeb, 0xa5, 0xac, 0x71, 0xcb, 0xa5, 0xac, 0xf5,
	0xd7, 0x19, 0xb6, 0x81, 0x63, 0xeb, 0xc6, 0xe9, 0xcb, 0x44, 0x0c, 0x6e, 0xf8, 0x8d, 0x7c, 0x79,
	0xcb, 0xc0, 0xf6, 0x58, 0xf3, 0x71, 0x7a, 0x1d, 0xff, 0x59, 0x01, 0x9f, 0x9b, 0xf1, 0x94, 0x5d,
	0x5e, 0xc0, 0x58, 0x87, 0xdf, 0x70, 0x9d, 0x49, 0x3d, 0xbb, 0xe9, 0x6f, 0xe6, 0x65, 0x2f, 0xfd,
	0xd5, 0x41, 0xbf, 0x04, 0x3b, 0xf5, 0xd8, 0xc6, 0xf3, 0xec, 0xf7, 0x39, 0x4a, 0xfd, 0xf1, 0xc9,
	0xb3, 0x05, 0xf5, 0x4f, 0xf0, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0x1b, 0x13, 0x4e, 0xa1,
	0x22, 0x00, 0x00,
}
