// Code generated by protoc-gen-go.
// source: dzhyun.blockstatistics.proto
// DO NOT EDIT!

package dzhyun

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TongJiApp struct {
	ChengJiaoE              int64                            `protobuf:"varint,1,opt,name=ChengJiaoE" json:"ChengJiaoE,omitempty"`
	LiuTongShiZhi           int64                            `protobuf:"varint,2,opt,name=LiuTongShiZhi" json:"LiuTongShiZhi,omitempty"`
	ZongShiZhi              int64                            `protobuf:"varint,3,opt,name=ZongShiZhi" json:"ZongShiZhi,omitempty"`
	ZhangDiePing            *TongJiApp_ZhangDiePingShuJu     `protobuf:"bytes,4,opt,name=ZhangDiePing" json:"ZhangDiePing,omitempty"`
	LingZhangGu             *TongJiApp_LingZhangGuShuJu      `protobuf:"bytes,5,opt,name=LingZhangGu" json:"LingZhangGu,omitempty"`
	TingPaiJiaShu           int64                            `protobuf:"varint,6,opt,name=TingPaiJiaShu" json:"TingPaiJiaShu,omitempty"`
	ZhangTingDieTing        *TongJiApp_ZhangTingDieTingShuJu `protobuf:"bytes,7,opt,name=ZhangTingDieTing" json:"ZhangTingDieTing,omitempty"`
	GuPiaoGeShu             int64                            `protobuf:"varint,8,opt,name=GuPiaoGeShu" json:"GuPiaoGeShu,omitempty"`
	PingJunJingTaiShiYingLv int64                            `protobuf:"varint,9,opt,name=PingJunJingTaiShiYingLv" json:"PingJunJingTaiShiYingLv,omitempty"`
	ZiJinJingE              int64                            `protobuf:"varint,10,opt,name=ZiJinJingE" json:"ZiJinJingE,omitempty"`
	ZiJinLiuXiang           []*TongJiApp_ZiJinLiuXiangShuJu  `protobuf:"bytes,11,rep,name=ZiJinLiuXiang" json:"ZiJinLiuXiang,omitempty"`
	JunJia                  int64                            `protobuf:"varint,12,opt,name=JunJia" json:"JunJia,omitempty"`
	JiaQuanJunJia           int64                            `protobuf:"varint,13,opt,name=JiaQuanJunJia" json:"JiaQuanJunJia,omitempty"`
}

func (m *TongJiApp) Reset()                    { *m = TongJiApp{} }
func (m *TongJiApp) String() string            { return proto.CompactTextString(m) }
func (*TongJiApp) ProtoMessage()               {}
func (*TongJiApp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *TongJiApp) GetChengJiaoE() int64 {
	if m != nil {
		return m.ChengJiaoE
	}
	return 0
}

func (m *TongJiApp) GetLiuTongShiZhi() int64 {
	if m != nil {
		return m.LiuTongShiZhi
	}
	return 0
}

func (m *TongJiApp) GetZongShiZhi() int64 {
	if m != nil {
		return m.ZongShiZhi
	}
	return 0
}

func (m *TongJiApp) GetZhangDiePing() *TongJiApp_ZhangDiePingShuJu {
	if m != nil {
		return m.ZhangDiePing
	}
	return nil
}

func (m *TongJiApp) GetLingZhangGu() *TongJiApp_LingZhangGuShuJu {
	if m != nil {
		return m.LingZhangGu
	}
	return nil
}

func (m *TongJiApp) GetTingPaiJiaShu() int64 {
	if m != nil {
		return m.TingPaiJiaShu
	}
	return 0
}

func (m *TongJiApp) GetZhangTingDieTing() *TongJiApp_ZhangTingDieTingShuJu {
	if m != nil {
		return m.ZhangTingDieTing
	}
	return nil
}

func (m *TongJiApp) GetGuPiaoGeShu() int64 {
	if m != nil {
		return m.GuPiaoGeShu
	}
	return 0
}

func (m *TongJiApp) GetPingJunJingTaiShiYingLv() int64 {
	if m != nil {
		return m.PingJunJingTaiShiYingLv
	}
	return 0
}

func (m *TongJiApp) GetZiJinJingE() int64 {
	if m != nil {
		return m.ZiJinJingE
	}
	return 0
}

func (m *TongJiApp) GetZiJinLiuXiang() []*TongJiApp_ZiJinLiuXiangShuJu {
	if m != nil {
		return m.ZiJinLiuXiang
	}
	return nil
}

func (m *TongJiApp) GetJunJia() int64 {
	if m != nil {
		return m.JunJia
	}
	return 0
}

func (m *TongJiApp) GetJiaQuanJunJia() int64 {
	if m != nil {
		return m.JiaQuanJunJia
	}
	return 0
}

// 领涨股
type TongJiApp_LingZhangGuShuJu struct {
	Obj               string `protobuf:"bytes,1,opt,name=Obj" json:"Obj,omitempty"`
	ZhongWenJianCheng string `protobuf:"bytes,2,opt,name=ZhongWenJianCheng" json:"ZhongWenJianCheng,omitempty"`
	ZuiXinJia         int64  `protobuf:"varint,3,opt,name=ZuiXinJia" json:"ZuiXinJia,omitempty"`
	ZhangFu           int64  `protobuf:"varint,4,opt,name=ZhangFu" json:"ZhangFu,omitempty"`
}

func (m *TongJiApp_LingZhangGuShuJu) Reset()                    { *m = TongJiApp_LingZhangGuShuJu{} }
func (m *TongJiApp_LingZhangGuShuJu) String() string            { return proto.CompactTextString(m) }
func (*TongJiApp_LingZhangGuShuJu) ProtoMessage()               {}
func (*TongJiApp_LingZhangGuShuJu) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 0} }

func (m *TongJiApp_LingZhangGuShuJu) GetObj() string {
	if m != nil {
		return m.Obj
	}
	return ""
}

func (m *TongJiApp_LingZhangGuShuJu) GetZhongWenJianCheng() string {
	if m != nil {
		return m.ZhongWenJianCheng
	}
	return ""
}

func (m *TongJiApp_LingZhangGuShuJu) GetZuiXinJia() int64 {
	if m != nil {
		return m.ZuiXinJia
	}
	return 0
}

func (m *TongJiApp_LingZhangGuShuJu) GetZhangFu() int64 {
	if m != nil {
		return m.ZhangFu
	}
	return 0
}

// 涨跌平
type TongJiApp_ZhangDiePingShuJu struct {
	ShangZhangJiaShu int64 `protobuf:"varint,1,opt,name=ShangZhangJiaShu" json:"ShangZhangJiaShu,omitempty"`
	XiaDieJiaShu     int64 `protobuf:"varint,2,opt,name=XiaDieJiaShu" json:"XiaDieJiaShu,omitempty"`
	PingPanJiaShu    int64 `protobuf:"varint,3,opt,name=PingPanJiaShu" json:"PingPanJiaShu,omitempty"`
}

func (m *TongJiApp_ZhangDiePingShuJu) Reset()                    { *m = TongJiApp_ZhangDiePingShuJu{} }
func (m *TongJiApp_ZhangDiePingShuJu) String() string            { return proto.CompactTextString(m) }
func (*TongJiApp_ZhangDiePingShuJu) ProtoMessage()               {}
func (*TongJiApp_ZhangDiePingShuJu) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 1} }

func (m *TongJiApp_ZhangDiePingShuJu) GetShangZhangJiaShu() int64 {
	if m != nil {
		return m.ShangZhangJiaShu
	}
	return 0
}

func (m *TongJiApp_ZhangDiePingShuJu) GetXiaDieJiaShu() int64 {
	if m != nil {
		return m.XiaDieJiaShu
	}
	return 0
}

func (m *TongJiApp_ZhangDiePingShuJu) GetPingPanJiaShu() int64 {
	if m != nil {
		return m.PingPanJiaShu
	}
	return 0
}

// 涨停跌停
type TongJiApp_ZhangTingDieTingShuJu struct {
	ZhangTingJiaShu int64 `protobuf:"varint,1,opt,name=ZhangTingJiaShu" json:"ZhangTingJiaShu,omitempty"`
	DieTingJiaShu   int64 `protobuf:"varint,2,opt,name=DieTingJiaShu" json:"DieTingJiaShu,omitempty"`
}

func (m *TongJiApp_ZhangTingDieTingShuJu) Reset()         { *m = TongJiApp_ZhangTingDieTingShuJu{} }
func (m *TongJiApp_ZhangTingDieTingShuJu) String() string { return proto.CompactTextString(m) }
func (*TongJiApp_ZhangTingDieTingShuJu) ProtoMessage()    {}
func (*TongJiApp_ZhangTingDieTingShuJu) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 2}
}

func (m *TongJiApp_ZhangTingDieTingShuJu) GetZhangTingJiaShu() int64 {
	if m != nil {
		return m.ZhangTingJiaShu
	}
	return 0
}

func (m *TongJiApp_ZhangTingDieTingShuJu) GetDieTingJiaShu() int64 {
	if m != nil {
		return m.DieTingJiaShu
	}
	return 0
}

// 资金流向
type TongJiApp_ZiJinLiuXiangShuJu struct {
	ShiJian    int64 `protobuf:"varint,1,opt,name=ShiJian" json:"ShiJian,omitempty"`
	ZiJinJingE int64 `protobuf:"varint,2,opt,name=ZiJinJingE" json:"ZiJinJingE,omitempty"`
}

func (m *TongJiApp_ZiJinLiuXiangShuJu) Reset()                    { *m = TongJiApp_ZiJinLiuXiangShuJu{} }
func (m *TongJiApp_ZiJinLiuXiangShuJu) String() string            { return proto.CompactTextString(m) }
func (*TongJiApp_ZiJinLiuXiangShuJu) ProtoMessage()               {}
func (*TongJiApp_ZiJinLiuXiangShuJu) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 3} }

func (m *TongJiApp_ZiJinLiuXiangShuJu) GetShiJian() int64 {
	if m != nil {
		return m.ShiJian
	}
	return 0
}

func (m *TongJiApp_ZiJinLiuXiangShuJu) GetZiJinJingE() int64 {
	if m != nil {
		return m.ZiJinJingE
	}
	return 0
}

func init() {
	proto.RegisterType((*TongJiApp)(nil), "dzhyun.TongJiApp")
	proto.RegisterType((*TongJiApp_LingZhangGuShuJu)(nil), "dzhyun.TongJiApp.LingZhangGuShuJu")
	proto.RegisterType((*TongJiApp_ZhangDiePingShuJu)(nil), "dzhyun.TongJiApp.ZhangDiePingShuJu")
	proto.RegisterType((*TongJiApp_ZhangTingDieTingShuJu)(nil), "dzhyun.TongJiApp.ZhangTingDieTingShuJu")
	proto.RegisterType((*TongJiApp_ZiJinLiuXiangShuJu)(nil), "dzhyun.TongJiApp.ZiJinLiuXiangShuJu")
}

func init() { proto.RegisterFile("dzhyun.blockstatistics.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0x37, 0xd0, 0xdd, 0x4c, 0xb6, 0x22, 0x58, 0x02, 0xac, 0x6a, 0x85, 0xaa, 0xb2, 0x12,
	0x15, 0x42, 0x3d, 0x2c, 0x17, 0xae, 0x40, 0x97, 0x4a, 0x51, 0x05, 0x25, 0xa9, 0x44, 0xc9, 0xcd,
	0x2d, 0x91, 0x3d, 0x7c, 0x38, 0x15, 0xad, 0x91, 0xe0, 0x1f, 0xc0, 0xdf, 0xe3, 0x0f, 0x21, 0x8f,
	0xd3, 0x36, 0x4e, 0x76, 0x4f, 0xe9, 0xbc, 0x79, 0x33, 0x6f, 0xc6, 0x7e, 0x2e, 0x5c, 0x7c, 0xfe,
	0xad, 0x7e, 0x19, 0x3d, 0x5e, 0x7d, 0x2b, 0xd7, 0x5f, 0xb7, 0x3b, 0xb1, 0xc3, 0xed, 0x0e, 0xd7,
	0xdb, 0xf1, 0xe6, 0x47, 0xb9, 0x2b, 0x59, 0xd7, 0x65, 0x87, 0xff, 0xce, 0x20, 0x5c, 0x94, 0x5a,
	0x26, 0xf8, 0x6a, 0xb3, 0x61, 0x8f, 0x01, 0xde, 0xa8, 0xc2, 0x46, 0xa2, 0xbc, 0xe6, 0x9d, 0x41,
	0x67, 0x14, 0xa4, 0x35, 0x84, 0x5d, 0x42, 0x6f, 0x86, 0xc6, 0xf2, 0x33, 0x85, 0xb9, 0x42, 0x7e,
	0x42, 0x14, 0x1f, 0xb4, 0x5d, 0xf2, 0x23, 0x25, 0x70, 0x5d, 0x8e, 0x08, 0x9b, 0xc2, 0x79, 0xae,
	0x84, 0x96, 0x13, 0x2c, 0xe6, 0xa8, 0x25, 0xbf, 0x33, 0xe8, 0x8c, 0xa2, 0xab, 0x27, 0xe3, 0x6a,
	0xe0, 0xc3, 0x38, 0xe3, 0x3a, 0x2b, 0x53, 0x26, 0x31, 0xa9, 0x57, 0xc8, 0x26, 0x10, 0xcd, 0x50,
	0x4b, 0xc2, 0xa6, 0x86, 0xdf, 0xa5, 0x3e, 0xc3, 0x76, 0x9f, 0x1a, 0xc9, 0xb5, 0xa9, 0x97, 0xd9,
	0xa5, 0x16, 0xa8, 0xe5, 0x5c, 0x60, 0x82, 0x22, 0x53, 0x86, 0x77, 0xdd, 0x52, 0x1e, 0xc8, 0x32,
	0x88, 0xa9, 0xc0, 0xa2, 0x13, 0x2c, 0xec, 0x87, 0x9f, 0x92, 0xe0, 0xd3, 0x5b, 0x06, 0xaf, 0x31,
	0x9d, 0x6a, 0xab, 0x01, 0x1b, 0x40, 0x34, 0x35, 0x73, 0x14, 0xe5, 0xb4, 0xb0, 0xc2, 0x67, 0x24,
	0x5c, 0x87, 0xd8, 0x4b, 0x78, 0x64, 0x57, 0x4d, 0x8c, 0x4e, 0x50, 0xcb, 0x85, 0xc0, 0x4c, 0xe1,
	0x27, 0xd4, 0x72, 0xf6, 0x93, 0x87, 0xc4, 0xbe, 0x2d, 0x4d, 0xb7, 0x80, 0x09, 0x52, 0xe2, 0x9a,
	0x43, 0x75, 0x0b, 0x07, 0x84, 0x25, 0xd0, 0xa3, 0x68, 0x86, 0x66, 0x89, 0x42, 0x4b, 0x1e, 0x0d,
	0x82, 0x51, 0x74, 0x75, 0x79, 0xc3, 0x36, 0x75, 0x9a, 0x5b, 0xc5, 0x2f, 0x65, 0x0f, 0xa1, 0x4b,
	0x23, 0x08, 0x7e, 0x4e, 0x3a, 0x55, 0x64, 0x8f, 0x36, 0x41, 0xf1, 0xc1, 0x08, 0x5d, 0xa5, 0x7b,
	0xee, 0x68, 0x3d, 0xb0, 0xff, 0xb7, 0x03, 0x71, 0xf3, 0x8a, 0x58, 0x0c, 0xc1, 0xfb, 0xd5, 0x17,
	0xf2, 0x60, 0x98, 0xda, 0x9f, 0xec, 0x39, 0xdc, 0xcf, 0x55, 0xa9, 0xe5, 0xc7, 0xc2, 0x56, 0x69,
	0xb2, 0x25, 0x19, 0x30, 0x4c, 0xdb, 0x09, 0x76, 0x01, 0x61, 0x6e, 0x70, 0x89, 0x24, 0xeb, 0x3c,
	0x78, 0x04, 0x18, 0x87, 0x53, 0x52, 0x7b, 0x6b, 0xc8, 0x7d, 0x41, 0xba, 0x0f, 0xfb, 0x7f, 0x3a,
	0x56, 0xa6, 0xe1, 0x3b, 0xf6, 0x0c, 0xe2, 0xcc, 0x82, 0x94, 0xa9, 0x6c, 0xe2, 0x9e, 0x47, 0x0b,
	0x67, 0x43, 0x38, 0x5f, 0xa2, 0x98, 0x60, 0x51, 0xf1, 0xdc, 0x1b, 0xf1, 0x30, 0x7b, 0x30, 0x73,
	0xb2, 0x97, 0xae, 0x48, 0x6e, 0x42, 0x1f, 0xec, 0x4b, 0x78, 0x70, 0xa3, 0x93, 0xd8, 0x08, 0xee,
	0x1d, 0x12, 0xde, 0x34, 0x4d, 0xd8, 0x0a, 0x55, 0x95, 0xde, 0x34, 0x3e, 0xd8, 0x7f, 0x07, 0xac,
	0x7d, 0xc9, 0xf6, 0x90, 0x32, 0x65, 0xfd, 0xaf, 0xab, 0xee, 0xfb, 0xb0, 0xe1, 0xad, 0x93, 0xa6,
	0xb7, 0x5e, 0x33, 0x88, 0xd7, 0xe5, 0xf7, 0xbd, 0x93, 0xe8, 0x1f, 0x67, 0xd5, 0xa5, 0xcf, 0x8b,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x17, 0x6f, 0xf5, 0x98, 0x04, 0x00, 0x00,
}
